### ISSUE TITLE
Postgresql connect issue with DB from Azure 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#1431]
### What version of UAA are you running?

74.27.0

### How are you deploying the UAA?

I am deploying the UAA

- using a bosh release I downloaded from bosh.io

### What did you do?

Updated from 74.26.0 to 74.27.0. The postgres DB provisioned from Azure rejected connection from uaa.
We manually checked the postgresql version in uaa.war to analyze that as reason.

In 74.26.0 the version 42.2.12 is used , in 74.27.0 42.2.16 is used.
If we switch back tio 74.26.0 we have the issue with #1347 and even more we found that
in version 74.26.0 there are libraries

"spring-beans" % "5.2.6.RELEASE"
"spring-context" % "5.2.6.RELEASE"
"spring-core" % "5.2.6.RELEASE"

which re-opens the issue https://tanzu.vmware.com/security/cve-2020-5421

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expect uaa with 
"spring-beans" % "5.2.9.RELEASE"
"spring-context" % "5.2.9.RELEASE"
"spring-core" % "5.2.9.RELEASE"
and 
https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.18

## Because:
We manually patched the uaa and with postgresql driver 42.2.18 the Azure issue is fixed,
because of gssEncMode setting is fixed

### What did you see instead?

Connect postgresql DB and a successful uaa startup

**Comment by shamus** [comment]
I looked into the spring version mismatch after we spoke yesterday. Because of the way the project is setup, the `springBootVersion` [property](https://github.com/cloudfoundry/uaa/blob/develop/dependencies.gradle#L15) determines the version of `spring-framework-bom`, not the `springVersion` [property](https://github.com/cloudfoundry/uaa/blob/develop/dependencies.gradle#L19). `springVersion` is vestigial.  

In `v74.26.0` the `springBootVersion` is `2.3.0.RELEASE`. The spring framework dependencies are then determined by [spring-boot-dependencies](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.3.0.RELEASE), which will bring in spring framework 5.2.6. 

In `v74.27.0` I see that `springBootVersion` is `2.3.4.RELEASE` which will result in the inclusion of spring framework 5.2.9.

I agree this is confusing; the dependencies file should not express `springVersion` if it is overridden by `springBootVersion`. I have put a story into the backlog to address the problem: https://www.pivotaltracker.com/story/show/175451332

Hopefully that provides some clarity.

That said, it sounds like the main issue here is that you're having trouble connecting to an Azure postgresql instance. This [github issue](https://github.com/pgjdbc/pgjdbc/issues/1868) covers the topic pretty thoroughly. From what I can tell this is a problem with Azure. That github issue reports Azure is providing a fix, but it isn't timely.  

I see that you've included a PR to pin the postgres JDBC library ahead to the latest version. As discussed previously, we'd like to avoid pinning versions of transitive dependencies if possible, allowing them to be managed by the spring BOMs. I see that the postgres JDBC team recommends adding `gssEncMode=disable` to the provided database url. Have you tried this solution as a work around until Azure sorts itself out?

**Comment by strehle** [comment]
I created this issue because of following conflict

- If we use the latest uaa bosh release we are free of known CVEs but we cannot run it in Azure.
- If we use the version prio to the lastest , then we see various CVEs, e.g. postgres but also spring framework.

I see that issue inside jdbc driver and this is packed with uaa.war so I dont see it as Azure issue.
We proofed that with version 42.2.18 the issue, which was obviously introduced with 42.2.15 , is fixed.

So what I ask you is, to provide a uaa release with postgresql 42.2.18, either via spring boot update (which might come later) or with an extra dep. update, and for safing your time i created the PR.

I asked our Ops colleges to set the database url with this arbitrary setting, but they dont know, therefore , if you mean that is possible, please provide details on that.

What we have is
url: jdbc:postgresql://XXXXXX.database.azure.com:5432/uaadb?sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory

So  if I look into
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/config/uaa.yml.erb#L258-L269
then we may can set uaadb with "uaadb?gssEncMode=disable", but then we could probably get

url: jdbc:postgresql://XXXXXX.database.azure.com:5432/uaadb?gssEncMode=disable?sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory

Further recommendations?

Thanks

**Comment by shamus** [comment]
I see. Yes, [uaa-release](https://github.com/cloudfoundry/uaa-release) would have to be extended to accept extra db connection parameters.  I think that might be more durable solution, as it gives some flexibility to work with the different cloud SQL providers.
 
I could imagine the uaa job spec being extended something like this:

```
  uaadb.connectionProperties:
    gssEncMode: disable
    someOtherProperty: someValue
```

Essentially a map of vendor specific connection properties. That map of values would then be appended to the connection url.

Thoughts?

**Comment by strehle** [comment]
So I agree on a vendor specific property map

Maybe you add this to YAML and the existing class
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/db/DatabaseUrlModifier.java, e.g. already adds the timeout for connect

Extending the bean
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/resources/spring/data-source.xml#L11-L15
would allow the setting in yml files or a system property/env.

Because:
if bosh is going to be retired with k8s, this enhancement could still be used.

The issue (we have) could be solve if spring publish its new release and it looks like they do it today, e.g. https://github.com/spring-projects/spring-boot/releases ... so if this 2.3.x version is out can we get then a new uaa-release with the update ?

**Comment by shamus** [comment]
Would you like to create PRs for this functionality?

**Comment by strehle** [comment]
yes I can do
