### ISSUE TITLE
Revoking single token doesn't work

### ISSUE THREAD

**Issue by samu** [cloudfoundry/uaa#1521]
### What version of UAA are you running?

74.29.0

### How are you deploying the UAA?

I'm not sure, since i don't operate it.

### What did you do?

I'm trying to revoke a single token. It's a JWT token, so i'm using the `jti` as described in the docs:

> For JWT tokens use the jti claim in the token.

```
curl --request DELETE \
  --url .../oauth/token/revoke/de443312ab6c42cb9faa6b31f1499b46 \
  --header 'Authorization: Bearer de443312ab6c42cb9faa6b31f1499b46'
```

It's a token i generated fresh with `cf oauth-token`.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Token is sucessfully revoked.

### What did you see instead?

```
{
  "error": "invalid_token",
  "error_description": "The token expired, was revoked, or the token ID is incorrect."
}
```

**Comment by bruce-ricard** [comment]
Hi @samu , thank you for the report. 

The first remark I would like to make is that IMHO it makes not much sense to try to revoke a JWT token. The reason for that is that JWT tokens are very often not validated against the UAA but using "offline validation".
I personally think that the UAA should refuse to revoke JWT tokens, because it makes no sense IMHO to do so.

If you really care about being able to revoke tokens at the exact moment you request it, you should be using opaque tokens.

What a lot of users do is that they use JWT tokens with a validity of a couple of hours. And they have refresh tokens with a longer validity. That way, if you revoke a user or client, they'll still be able to use their current access token until it expires an hour later, but they won't be able to use their refresh token to get a new access token.

Please let me know what you think, thank you.

**Comment by samu** [comment]
Hi @bruce-ricard ,

thanks for your reply. I don't think the discussion here should be based on personal opinion. [Token Revocation](https://tools.ietf.org/html/rfc7009#page-3) is an OAuth Standard and should therefore be supported.

My personal opinion resembles yours: i don't think it is absolutely crucial to be able to revoke tokens, since they can be given a short life-span and will expire at some point.

If you decide not to implement this feature, please state so in the documentation.

**Comment by bruce-ricard** [comment]
Hi @samu 

Thank you for sharing the RFC link.

> I don't think the discussion here should be based on personal opinion

I absolutely agree. The issue is that the RFC isn't clear. For example, you say:

> Token Revocation is an OAuth Standard and should therefore be supported

The RFC indeed [states](https://tools.ietf.org/html/rfc7009#page-2:~:text=Implementations%20MUST%20support%20the%20revocation%20of,support%20the%20revocation%20of%20access%20tokens)

> Implementations MUST support the revocation of refresh tokens and
   SHOULD support the revocation of access tokens

But it seems to me like the document is only talking about opaque tokens, even though it is never explicitly stated. I say that for two reasons:

1. These lines of the RFC: 
    1. This [statement](https://tools.ietf.org/html/rfc7009#page-2:~:text=A%20token%20is%20a%20string%20representing,the%20resource%20owner%20to%20the%20client): A token is a string representing an authorization grant issued by the resource owner to the client
    2. This [code snippet](https://tools.ietf.org/html/rfc7009#page-4:~:text=token%3D45ghiukldjahdnhzdauz%26token_type_hint%3Drefresh_token): token=45ghiukldjahdnhzdauz, showing an opaque token
1. I maintain that revoking JWT tokens makes no sense, since some resource servers may bypass the revocation by using offline token validation. This gives a false sense of security to the client, which IMO is worse than known bad security.

IMHO the document doesn't mention transparent tokens because it's obvious that they can't be revoked. 

But please let me know if you think there's a flaw in my reasoning.

> If you decide not to implement this feature, please state so in the documentation.

I absolutely agree. TBH I am surprised that you are getting this error, I thought that revocation of JWT token was supposed to work from what I had read.

**Comment by samu** [comment]
I don't fully follow your line of arguments since i simply don't know enough about this topic and the underlying implementation details. I can try to shed some light from another (non technical) angle:

1. If a user logs in to a system (e.g. by providing username/password), they expect there to be a way to log out, i.e. invalidating the session. This is especially important for systems which require a high level of security, such as online banking, where it is recommended to log out as soon as you're done with your work. I don't see how token revocation is any different: if a user has obtained a token (e.g. via `cf oauth-token`), they might want to invalidate that token (i.e. log out) as soon as they're done with their work.

2. If we look at the matter from the eyes of a security expert, we'd try to handle any kind of security matter with high priority: what can be done, should be done. If we can provide a log out button, provide it, if we can provide an endpoint to revoke a token, provide it, etc. Any kind of improvement we can do to increase the security of a system should be evaluated very seriously, regardless of how important it is. 

I don't know enough about the uaa internals, but i think this discussion should also involve taking into account the tradeoff between implementation complexity and benefit for the end user. If the feature can be implemented with relatively low efforts, then why not simply do it.

As i said before, i don't want to force this - at the end of the day i just need to give a potential ETA (or declining) to my bosses.

**Comment by bruce-ricard** [comment]
I would like to start by saying how grateful I am that you are explaining your problems. It is very valuable to us to understand how our users use our product and it helps us improve that product. So thank you for that.

> we'd try to handle any kind of security matter with high priority: what can be done, should be done.

I care a lot about security and I agree with you. In my mind, security is paramount, especially with products like the UAA and especially when used in the context of a bank like you said.

> if we can provide an endpoint to revoke a token, provide it

I would like to really emphasize the fact that **no one** *really* can revoke a transparent token, by design.
You said that security is very important to you. And I said that I agreed. But IMHO, there is one thing that is worse than bad security: a false sense of security. If you call the `revoke` endpoint with a JWT token that you had shared with me, and the UAA told you that the token was revoked, I could *still use* the token, because resource servers wouldn't contact the UAA when validating it to know if it is revoked or not. That would give you a false sense of security, which IMHO is the worst. I am glad that your UAA returned this error and made you contact us.  I want to be sure that we are on the same page on this topic. 

If you are unhappy with this behavior and absolutely need tokens to be unusable at the second they are revoked, I recommend configuring your UAA to use opaque tokens. By design, with opaque tokens, receivers of a token have no option but to contact the UAA to figure out which permissions the token represents.

> If a user logs in to a system (e.g. by providing username/password), they expect there to be a way to log out, i.e. invalidating the session. This is especially important for systems which require a high level of security, such as online banking, where it is recommended to log out as soon as you're done with your work.

Absolutely agree.

> I don't see how token revocation is any different: if a user has obtained a token (e.g. via cf oauth-token), they might want to invalidate that token (i.e. log out) as soon as they're done with their work.

I'm going to try to explain why it is different with tokens. 

First of all, tokens are **not** for users. Users should never see the tokens. Tokens are for users to give permission to certain apps (called clients in the OAuth spec) to act on their behalf. There is no concept of logging out in OAuth. A user gives a authorization to a client to do something on their behalf for a certain amount of time, and that's all there is to it. Revoking tokens should not be part of the day to day, typical workflow.
Revoking tokens is for emergency situations like for example: a client just became compromised and you want to revoke all tokens it might have, or a token got leaked somehow and you want to revoke it etc.

I understand that this is confusing to a lot of people, especially since OAuth likes to call its thing "Login with Facebook", which makes it sound like it's like a login, but it's really not. It took me a while myself...

**Comment by samu** [comment]
> If you call the revoke endpoint with a JWT token that you had shared with me, and the UAA told you that the token was revoked, I could still use the token, because resource servers wouldn't contact the UAA when validating it to know if it is revoked or not.

Thanks for stating that again, because i didn't understand it before. If there's technical limitations to revoking tokens, i can totally accept that as a conclusion of this conversation.

> First of all, tokens are not for users. Users should never see the tokens.

Just as a small hint: i have used `cf oauth-token` before in order to do calls with `cf api`.

**Comment by bruce-ricard** [comment]
> Just as a small hint: i have used `cf oauth-token` before in order to do calls with `cf api`.

Yes I agree. This is a bit of a hack around OAuth to be used by CLIs. Technically, **you** are not getting the token. You are giving one to the CLI client to make requests on your behalf. It's a bit confusing because in this particular case you both are on the same machine, and you can look at the token by finding it on the filesystem...

**Comment by samu** [comment]
> and you can look at the token by finding it on the filesystem

no, the token is printed to the console and then i copy-paste it to wherever i want. For example, i frequently copy it into Postman App.

**Comment by bruce-ricard** [comment]
Sorry Samu, I forgot about this thread. 

You are right. This command allows you to see the token so that you can give it to other clients. In an ideal world, the token would be sent to other clients without you having to interact with it and see it, but it's complicated in the CLI case.
