### ISSUE TITLE
Issue with JWT bearer token grant in case the initial JWT was issued by the UAA

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#1529]
### What version of UAA are you running?

75.0.0

### How are you deploying the UAA?

I am deploying the UAA using cf-deployment

### What did you do?

* cf login
* cf oauth-token
* POST to /oauth/token with JWT bearer token grant

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expect to get a token of the user from which I initially retrieved the oauth token via "cf oauth-token".

### What did you see instead?

A new shadow user was created based on the "sub" claim of the JWT retrieved via "cf oauth-token". And the retrieved JWT was issued for that newly created shadow user.

**Details**
During JWT Bearer with an UAA-issued token, the UAA constructs an internal Identity Provider config that is used in the authentication of JWT Bearer. This internal config does not define any [attributeMappings](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java#L174-L181).

The issue seems to appear after the merge of [PR#1330](https://github.com/cloudfoundry/uaa/pull/1330) which caused the user to be updated when the externalID changes, including the username. And as the attribute mapping is empty, the default is used, which is the "sub" claim of the token. But it should be "username" to "username".

We will provide a PR that fixes the issue.

**Comment by peterhaochen47** [comment]
Thanks @torsten-sap, we started looking at this. May I ask you to clarify your description of the reproduction steps? Since these steps involve multiple tokens and multiple "retrieval" processes, it's not clear which tokens you are referring to at different points. Let me do some guess-work & try to rephrase the description:

**What did you do?**
- Run `cf login` with `user-a`, ~~a UAA internal user (aka not from an external IDP)~~ a user from an external IDP that us integrated with UAA.
- Run `cf oauth-token`, capture the outputted access token `access-token-foo`; When I decode `access-token-foo`, I can see its `user_name` claim is `user-a` and `sub` claim is `sub-user-a` (just an example value; the `sub` claim is usually the user id)
- POST to /oauth/token with [JWT bearer token grant](https://docs.cloudfoundry.org/api/uaa/version/75.0.0/index.html#jwt-bearer-token-grant), where the request param `assertion` is `access-token-foo`; UAA responds with an access token `access-token-bar`.
 
**What did you expect to see? What goal are you trying to achieve with the UAA?**
- I expect `access-token-bar` is for the user `user-a`. Aka, when I decode `access-token-bar`, the `user_name` claim should be `user-a`.
 
**What did you see instead?**
- When I decode `access-token-bar`, the `user_name` claim is `sub-user-a`.
- In UAA database, a new shadow user was created based on the `sub` claim of `access-token-foo` (the JWT retrieved via `cf oauth-token`). And the retrieved JWT `access-token-bar` was issued for that newly created shadow user.

Please correct me if that's not what you meant. 
I will separately address the PR soon. I just wanna make sure we are aligned on the reproduction steps first.

**Comment by tack-sap** [comment]
Hi @peterhaochen47,

In general the flow as you describe it looks good. 
However this is not restricted to UAA internal users, but also happens for users of external IdPs (in our use case we always have such an external IdP user - I have not tested UAA internal users explicitly, but as there is no mechanism to identify those at that part of the code, it probably holds also for them). 
The important part is, that the `access-token-foo` that is used for the JWT Bearer was issued by the UAA itself.

**Comment by peterhaochen47** [comment]
Thanks @tack-sap, I have corrected the description in my comment. Now I understand the issue, I will add comments + questions in the PR #1530 now.

**Comment by torsten-sap** [comment]
Closing as PR was merged.
