### ISSUE TITLE
unable to receive email verification after creating account

### ISSUE THREAD

**Issue by henryyue2010** [cloudfoundry/uaa#1588]
I tried to config smtp.gmail.com: 587 or 465 in uaa.yml

both port do not work

Anyone knows how to config a smtp server or how to skip the email verification in the process of authorization?

Thank you.

**Comment by strehle** [comment]
as uaa admin you can set the email verified, see
https://docs.cloudfoundry.org/api/uaa/version/75.2.0/index.html#verify-user
this is if user was created via invite or API.

if user was created as shadow user via OIDC then ensure that claim email_verified = true is set in id_token from IDP authentication

**Comment by strehle** [comment]
hi,
closes this because in last version we have added a TLS property.
https://github.com/cloudfoundry/uaa-release/pull/305/files

All SMTP/Email properties for bosh , see
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L425-L450

If you further problems in setup, provide an error message, 

best regards
