### ISSUE TITLE
uaac client is not able to set "autoapprove true" for client ids

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/uaa#162]
After our migration from CF 205 to CF 210, we can no longer set autoapprove again. This was fixed in the past and is now broken again.

There are two distinct but related problems:
1. Setting autoapprove to true during creation of an ID does not get reflected in the DB
2. Setting autoapprove to true after creation of an ID does not get reflected in the DB

....

1. A recently created id:

scope: cloud_controller.read openid
client_id: cdsx
resource_ids: none
authorized_grant_types: authorization_code client_credentials refresh_token
redirect_uri: http://localhost:8080 https://cdsx.stage1.ng.bluemix.net
**autoapprove:**
authorities: cloud_controller.read openid

If you see autoapprove is blank there.

2. After creation (see attached/obscured trace output)

uaac client update cloudregistration --autoapprove false
  scope: openid
  client_id: cloudregistration
  authorized_grant_types: refresh_token client_credentials authorization_code
  redirect_uri: ....
  **autoapprove: false**

Right after that invocation, I try to double-check the value:

uaac client get cloudregistration
  scope: openid
  client_id: cloudregistration
  resource_ids: none
  authorized_grant_types: authorization_code client_credentials refresh_token
  redirect_uri: ...
  **autoapprove: true**

**Comment by fhanik** [comment]
Thank you for the report @fraenkel 
The behavior has changed a little bit since we had to consolidate the usage of autoapprove (as a field in additionalInformation) and autoapprove that became a new field with a Spring Security OAuth2 upgrade.

Here is how the system works

When a client is saved the following takes place

    if (one of the values of the autoapprove set has a value of true) {
        store the value 'true' in the database
    } else {
        List autoapprovedScopesToBeStored;
        for each client scope {
            if (scope is in the autoapprove set) {
                autoapprovedScopesToBeStored.add(scope)
            }
        }
        store autoapprovedScopesToBeStored in DB
    }

This has some side effects
1. The only values in the DB can be true or a list of valid scopes to be auto approved
2. The value false is completely ignored - an empty list in the DB is the same as false
3. If you add a scope to the autoapprove set that is not part of the --scope set, it will be ignored

I have added a minor fix, so that the return value of the call returns what is actually reflected in the DB, and not what was passed up as a parameter
fbc61ab0132c48f060c9a47c93baaa909f332a77
