### ISSUE TITLE
Build fails doclint on JDK8

### ISSUE THREAD

**Issue by dcminter** [cloudfoundry/uaa#166]
Building as per the README.md with "./gradlew run" fails with JDK8 as a result of numerous doclint failures.

**Comment by mbultrow** [comment]
Tests also fail on Oracle JDK8 because of missing symbols.

**Comment by jdubois** [comment]
Same issue here, I cannot run UAA on my Mac with JDK8.

When doing a ```./gradlew run``` I have the following result:
```
30 errors
83 warnings
:cloudfoundry-identity-common:javadoc FAILED
```

It's really weird that I can't run the project because of the Javadoc :-)
But looking at the stacktrace it looks like a JDK8 issue - I'm really surprised that a CloudFoundry project doesn't work on JDK8!

**Comment by thomasdarimont** [comment]
Hi,

I just submitted the PR #186 which enables you to build uaa with Java 7 and Java 8.
It fixes all of the JavaDoc errors (alongside some warnings) and contains some tiny refactorings for places where internal sun.* API was used that isn't available anymore in Java 8.  

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
I suggest to close this issue, since #186 has been merged into master.
