### ISSUE TITLE
customization by using UAA as library in gradle/maven

### ISSUE THREAD

**Issue by HungUnicorn** [cloudfoundry/uaa#1692]
### What version of UAA are you running?
4.30.0
https://mvnrepository.com/artifact/org.cloudfoundry.identity/cloudfoundry-identity-server

### How are you deploying the UAA?

I am deploying the UAA
- as an dependecy in gradle

### What do you want to do?
I want to customize some code and use UAA as a lib, which one should I take? is this one? coz the version is not up-to-date
https://mvnrepository.com/artifact/org.cloudfoundry.identity/cloudfoundry-identity-server/4.30.0

I want to put the newest version https://github.com/cloudfoundry/uaa/tree/v75.8.0
 in my gradle file
```
implementation group: 'org.cloudfoundry.identity', name: 'cloudfoundry-identity-server', version: '7.58.0'
```

**Comment by strehle** [comment]
some year ago the maintainer of uaa decided to remove the tools part, e.g. client library (which was a subproject in uaa) and maven deployment, because the support load of such requests.

The uaa is bundled into uaa-release and accessible via bosh, see
https://bosh.io/releases/github.com/cloudfoundry/uaa-release?all=1
https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=75.8.0

Each release gets an own branch, see https://github.com/cloudfoundry/uaa/tree/75.8.0 which you can checkout and rebuild with
`./gradlew :clean :assemble -Pversion=75.8.0`

We support uaa only as deployment to CF, if you run UAA in an own environment or standalone then this needs own effort in software distribution

Hope this helps
