### ISSUE TITLE
Authentication via Idp does not trigger MFA and password expiration

### ISSUE THREAD

**Issue by gw-lling** [cloudfoundry/uaa#1697]
### What version of UAA are you running?
75.5.2

### How are you deploying the UAA?

kubernetes

### What did you do?

- Setup MFA and `requirePasswordChange: true` for a zone.
- Setup UAA as Idp.

### What did you expect to see? What goal are you trying to achieve with the UAA?

UAA should prompt for MFA and password change regardless login directly from UAA UI or through Idp.

### What did you see instead?

Login through UAA directly shows MFA and password change, but login Idp skips these 2 steps.

**Comment by strehle** [comment]
hi , I am not sure that I understand this therefore please let me ask.

With Idp you mean you have configured a SAML or OIDC idp in UAA, correct ?

MFA is defined by default to origins ldap and uaa, see similar issue #1648 
therefore I ask about if you have some IDP different which gets a different origin
https://github.com/cloudfoundry/uaa/issues/1648

About password change I am not sure but for SAML/OIDC this not make sense because in UAA you only have a shadow user but the authentication itself is done to external IDP incl. policies like passowrd change.
