### ISSUE TITLE
check_token behavior across UAA zones

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#172]
This is a bit of both open-ended question/issue we are experiencing with UAA.

We would like to build a service that can trust multiple UAA zones. Ideally, we would like a way to validate a token without having to make a web service call to /check_token and incur a round-trip penalty. After all, if the tokens are signed using asymmetric cryptography, why not reap the benefits? Couldn't we just transplant the server logic in the server-side RemoteTokenServices to the client-side RemoteTokenService? Perhaps there is already a way to do this? Ideally, our relying party would store a map of issuer ids and the public certificates to verify tokens from trusted issuers.

To work around this limitation in the near term, we would like to be able to call the default /check_token and have it validate tokens for all zones of a particular UAA deployment. For example, if I get a token like so:
uaac target http://testzone1.localhost:8080/uaa
uaac client token get some_client

I would like to be able to validate that token against:
http://localhost:8080/uaa/check_token

Currently, it complains about an issuer mismatch. It's not clear to me why UAA would not allow this, after all the signing credentials are the same across all zones, what do we gain by being strict about what the "iss" property of the token is?

**Comment by fhanik** [comment]
This is a feature that will not be supported. Tokens issued in a zone can only be validated in that zone. It is not simply about the 'iss' claim. The client that is using /check_token must be a valid client in the zone for that token. This is currently denoted by the subdomain, testzone1. You can't have a client try to validate a token for another zone. The client would never get authenticated. It would also prevent us from implementing more features around validation in the future too, such as who is allowed to invoke check_token, ideally it should only be the resource server that the token is issued for.

The fact that the keys are global today, just means that the configuration has not been zone-i-fied yet. But most likely will be, since changing the keys revokes all tokens, and should be done on a per zone basis.

If you wish to use http://localhost:8080/uaa/check_token for everything, then you probably don't need zones at all. Simply use the default zone for everything as well.

If we started to blur the lines between zones, we would start having major issues in a lot of endpoints. Such as uniqueness for a user, or a client. Or what different scopes mean.

**Comment by amiri-ge** [comment]
@fhanik I don't think this means that you don't need zones, we still want to keep identities separate. What it means is that we want a single endpoint that can check the identity for all zones. As per discovery of the token zone, the subdomain is not strictly necessary since this can be done by extracting "zid" from the JWT token. This could even be done by header as with some of the other endpoints.

But let's step back a bit, the root issue for us is that we want to build a service that can accept tokens for multiple zones. However, we don't want to store a client_id/client_secret in a database for each zone. How do you suggest we solve this problem?

**Comment by fhanik** [comment]
>However, we don't want to store a client_id/client_secret in a database for each zone.

You can't get a token in a zone without there being a client_id/client_secret in that zone.

I don't think I fully understand your use case here...maybe if you elaborate why a resource server needs to validate the token against another issuer?

Think of zones as different servers all together. ie zone1.uaa.domain and zone2.uaa.domain could be hosted completely separated. The fact that they are cohosted in the same VM is an implementation detail. To the OAuth world, they are two separate OAuth servers.
