### ISSUE TITLE
K8s image outdated

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#1729]
### What version of UAA are you running?

75.9.0

### How are you deploying the UAA?

I am deploying the UAA

- docker

### What did you do?

run image from 
https://github.com/cloudfoundry/uaa/blob/develop/k8s/templates/values/image.yml#L3

docker run --privileged --tty --interactive --shm-size=1G --name test --rm -d cloudfoundry/uaa@sha256:4c7f2d881bc9c4a075232064e906d032c9512b03b87c06cbb2501560cb2f14e4

### What did you expect to see? What goal are you trying to achieve with the UAA?

latest or at least a new UAA version

### What did you see instead?

outdated UAA

created also issue https://github.com/cloudfoundry/uaa-k8s-release/issues/1

**Comment by peterhaochen47** [comment]
I'm still trying to rediscover context about how these images are managed. But currently, I see the the image reference is updated on the git branch/tag that is associated with each uaa release, eg this commit: https://github.com/cloudfoundry/uaa/commit/a04e905e69ad8f6339f040989b6862a6148b37da is on this branch https://github.com/cloudfoundry/uaa/tree/v75.11.0

And the `develop` branch one is indeed outdated for months due to the relevant CI job's failure. Will look more into it.

**Comment by strehle** [comment]
Hi Peter,
context is the setup of UAA in K8s , e.g. I setup uaa on minikube and there I see setup issue, . I see that our acceptance UAA https://uaa.uaa-acceptance-k8s.cf-app.com/info is recent enough but  does not work, https://uaa.uaa-acceptance-k8s.cf-app.com/login
