### ISSUE TITLE
Microsoft SQL Server Support

### ISSUE THREAD

**Issue by singh-gurpreet** [cloudfoundry/uaa#1751]
UAA isn't able to work with Microsoft SQL Server anymore, please help how latest version can work with MicroSoft SQL Server

Unable to obtain connection from database: Unable to load class: com.microsoft.sqlserver.jdbc.SQLServerDriver from ClassLoader:ParallelWebappClassLoader

**Comment by strehle** [comment]
It was removed in version 4.31, see
https://github.com/cloudfoundry/uaa/releases/tag/4.31.0
with 
https://github.com/cloudfoundry/uaa/commit/14ed2fac2bd1450eb08133528be1267142528891

More than 2 years ago

**Comment by singh-gurpreet** [comment]
thank you @strehle how I can make it work SQL Server, we had 4.19, now time to upgrade and now there is no MicroSoft SQL Server

**Comment by strehle** [comment]
Here I found initial PR for MS SQL server support
https://github.com/cloudfoundry/uaa/pull/507

From tags it refs. versionn 4.12.x

DB support in UAA is a time consuming business as you can see with the issues and PRs from history here. There are always issues with missing indexes and/or SQL incompatiblities during the various DBs and version. 
We have in meantime mysql and postgresql only. 

If you want (again) MSQL in there I assume you should ask in WG foundation
https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md
for support of MSQL in https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md#integrated-databases-1
@rkoster  ?

The other possibility is a fork but of course your fork should get upstream from here very often in order to consume all the security fixes, because a version 4.19.0 should not longer be accessibly to the outside world ...
