### ISSUE TITLE
UAA start-up fails

### ISSUE THREAD

**Issue by madpipeline** [cloudfoundry/uaa#1829]
### What version of UAA are you running?
75.15.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
None, UAA does not start.

### How Are you building UAA?
```
git clone --branch v${UAA_VERSION} --depth 1 https://github.com/cloudfoundry/uaa.git . && \
    ./gradlew --no-daemon :clean :assemble -Pversion=${UAA_VERSION}
```
### How are you deploying the UAA?
```
LOGGING_CONFIG="${LOGGING_CONFIG:-/usr/local/tomcat/lib/log4j2.properties}"
UAA_CONFIG_PATH="${UAA_CONFIG_PATH:-./usr/local/tomcat/webapps}"
export JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -DPID=$$ -Dnetworkaddress.cache.ttl=0 -Dlog4j.configurationFile=$LOGGING_CONFIG"
export CLASSPATH="/usr/local/tomcat/lib"
export UAA_CONFIG_PATH

[ -f "$UAA_CONFIG_PATH/uaa-template.yml" ] &&
  envsub -g <"${UAA_CONFIG_PATH}/uaa-template.yml" > "${UAA_CONFIG_PATH}/uaa.yml"
/usr/local/tomcat/bin/catalina.sh run
```
The uaa-template.yml file is a copy from https://github.com/cloudfoundry/uaa/blob/75.15.0/uaa/src/main/resources/uaa.yml with uncommented sections.

The DB section is:

```
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${POSTGRES_NAME}:5432/${DB}?currentSchema=uaa
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASS}
  maxactive: 100
  maxidle: 10
  minidle: 3
  removeabandoned: false
  logabandoned: true
  abandonedtimeout: 300
  evictionintervalms: 15000
  caseinsensitive: false
```

### What did you do?

Start the docker container containing UAA.

### What did you expect to see? What goal are you trying to achieve with the UAA?
UAA to start up.

### What did you see instead?
```
[2022-03-31T15:10:19.432Z] uaa/uaa - 142 [main] ....  INFO --- VersionPrinter: Flyway Community Edition 5.2.4 by Boxfuse
[2022-03-31T15:10:21.325Z] uaa/uaa - 142 [main] ....  INFO --- DatabaseFactory: Database: jdbc:postgresql://XXXX:5432/XXXX (PostgreSQL 12.6)
[2022-03-31T15:10:21.359Z] uaa/uaa - 142 [main] ....  WARN --- Database: Flyway upgrade recommended: PostgreSQL 12.6 is newer than this version of Flyway and support has not been tested.
[2022-03-31T15:10:21.379Z] uaa/uaa - 142 [main] ....  WARN --- XmlWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: 
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor#0' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: 
    Cannot resolve reference to bean 'identityZoneResolvingFilter' while setting bean property 'additionalFilters' with key [TypedStringValue: 
    value [#{T(org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor.FilterPosition).position(5)}], target type [null]]; 
        nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'identityZoneResolvingFilter' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: 
        Unsatisfied dependency expressed through constructor parameter 0; 
        nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'identityZoneProvisioning' defined in URL [jar:file:/usr/local/tomcat/webapps/uaa/WEB-INF/lib/cloudfoundry-identity-server-75.15.0.jar!/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioning.class]: 
        Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: 
        Error creating bean with name 'flyway' defined in org.cloudfoundry.identity.uaa.db.beans.FlywayConfiguration$FlywayConfigurationWithMigration: 
        Bean instantiation via factory method failed; 
        nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: 
        Factory method 'flyway' threw exception; 
        nested exception is org.flywaydb.core.api.FlywayException: 
        Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
[2022-03-31T15:10:21.395Z] uaa/uaa - 142 [main] .... ERROR --- DispatcherServlet: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor#0' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: 
    Cannot resolve reference to bean 'identityZoneResolvingFilter' while setting bean property 'additionalFilters' with key [TypedStringValue: 
    value [#{T(org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor.FilterPosition).position(5)}], target type [null]]; 
        nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'identityZoneResolvingFilter' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: 
        Unsatisfied dependency expressed through constructor parameter 0; 
        nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
        Error creating bean with name 'identityZoneProvisioning' defined in URL [jar:file:/usr/local/tomcat/webapps/uaa/WEB-INF/lib/cloudfoundry-identity-server-75.15.0.jar!/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioning.class]: 
        Unsatisfied dependency expressed through constructor parameter 0; 
        nested exception is org.springframework.beans.factory.BeanCreationException: 
        Error creating bean with name 'flyway' defined in org.cloudfoundry.identity.uaa.db.beans.FlywayConfiguration$FlywayConfigurationWithMigration: 
        Bean instantiation via factory method failed; 
        nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: 
        Factory method 'flyway' threw exception; 
        nested exception is org.flywaydb.core.api.FlywayException: 
        Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
```

**Comment by strehle** [comment]
Thanks for reporting this. Will check it. Currently UAA has 2 hard coded deps , one is flayway
https://github.com/cloudfoundry/uaa/blob/develop/dependencies.gradle#L6-L9

So I assume in past there were issues, thus the own version definition

**Comment by strehle** [comment]
Hi,
tested latest uaa startup from scratch with postgresql 12.6., 12.10, 13.5 and found no issue because of flyway.

Flyway bean is the first connect to DB so if there is an issue, then this bean fails, so from my expierence in past I know these kind of error in case of DB connection problems.

The warning at the begin I can see, too
>>>
[2022-04-02T11:54:31.332076Z] uaa/uaa - 5702 [main] ....  INFO --- VersionPrinter: Flyway Community Edition 5.2.4 by Boxfuse
[2022-04-02T11:54:31.571726Z] uaa/uaa - 5702 [main] ....  INFO --- DatabaseFactory: Database: jdbc:postgresql://postgresql:5432/cfuaa (PostgreSQL 12.6)
[2022-04-02T11:54:31.602019Z] uaa/uaa - 5702 [main] ....  WARN --- Database: Flyway upgrade recommended: PostgreSQL 12.6 is newer than this version of Flyway and support has not been tested.
[2022-04-02T11:54:31.659101Z] uaa/uaa - 5702 [main] ....  INFO --- JdbcTableSchemaHistory: Repair of failed migration in Schema History table "public"."schema_version" not necessary as table doesn't exist.
......
[2022-04-02T11:54:33.258113Z] uaa/uaa - 5702 [main] ....  INFO --- DbMigrate: Migrating schema "public" to version 4.101.1631562784 - Add LowerIndex To Users [non-transactional]
[2022-04-02T11:54:33.275597Z] uaa/uaa - 5702 [main] ....  INFO --- DbMigrate: Migrating schema "public" to version 4.101.1639764160 - Add LowerIndex To Users Wo Origin [non-transactional]
[2022-04-02T11:54:33.294014Z] uaa/uaa - 5702 [main] ....  INFO --- DbMigrate: Successfully applied 86 migrations to schema "public" (execution time 00:01.530s)
[2022-04-02T11:54:33.295633Z] uaa/uaa - 5702 [main] ....  INFO --- PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'flyway' of type [org.flywaydb.core.Flyway] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
<<<

**Comment by madpipeline** [comment]
If that's the case it seems my issue is not cause by Flyway but by something else, which I am still unable to identify.

**Comment by madpipeline** [comment]
It seems I didn't have the `uaa` schema created. After I created the schema, I was free of that error, and onto the next.
Shouldn't UAA create the schema if it doens't find it?

**Comment by strehle** [comment]
in postgresql the default schema is public and now I see the issue, your jdbcUrl specifies currentSchema different to public.
since the public schema in create db is always there it was never an issue for others. e.g.

`url: jdbc:postgresql://${POSTGRES_NAME}:5432/${DB}`

would solve it and use public schema always

**Comment by strehle** [comment]
I would close this issue and for later it will be found . I did not have found any other issue with similar use case, means
?currentSchema=xxx so if somebody else have same issue later on we could reverence this here.

**Comment by madpipeline** [comment]
Thank you for the clarification @strehle. I'll close the issue now.
