### ISSUE TITLE
Allow overriding Content security header

### ISSUE THREAD

**Issue by kr8n3r** [cloudfoundry/uaa#2086]
76.0.0 contains https://github.com/cloudfoundry/uaa/pull/1981/commits/72565fb56cd1f90af499119d32c891937f3c5a76 which disallows inline scripts.

On [GOV.UK PaaS ](https://login.cloud.service.gov.uk/login)we use javascript to improve some of the accessibility and on our customised passcode page to insert a copy code button that uses the clipboard api.

With the introduced change both of those things are no longer functional. 

Consider enabling a way to override the CSP settings.

**Comment by strehle** [comment]
@kr8n3r Can I move this issue to [uaa](https://github.com/cloudfoundry/uaa) ?  because the changes would be done around https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilter.java#L19 .

Do you (a) have need a better passcode copy code button or (b) is this request a general request for a customzied header Content-Security-Policy in https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/security/web/ContentSecurityPolicyFilter.java ?

If (a) please create a PR with your improvements. For (b) we should discuss with VMware colleagues because you want that we add additional domains in https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP ?

**Comment by kr8n3r** [comment]
Hi @strehle, yes please move to UAA.

We run customised UAA login and passcode page and not the default ones  for branding and accessibility reasons.
Any enhancement to the default copy would not be of any use to use so a way for us to amend / supercede default CSP rules is the only option. 

We customise pages [here](https://github.com/alphagov/paas-uaa-customized-boshrelease) and [here](https://github.com/alphagov/paas-cf/blob/main/manifests/cf-manifest/operations.d/330-uaa.yml)

**Comment by strehle** [comment]
Hi @kr8n3r 

so from you side you simply are fine with a switch to deactivate 'unsafe-inline' .?

regards,

**Comment by kr8n3r** [comment]
Hi @strehle ,  we would either do that or add a SHA

**Comment by swalchemist** [comment]
Adding a hash would allow the code to work without needing to change the Content Security Policy, right?

**Comment by kr8n3r** [comment]
> Adding a hash would allow the code to work without needing to change the Content Security Policy, right?

there is no way to add a hash as the hardcoded UAA server CSP overrides any local attempts on our side (like metatag hash addition)

**Comment by pburkholder** [comment]
Over here at cloud.gov we also need a way to override `script-src 'self'` with something like `script-src 'self' 'sha256-base64stuff…` in the release. There's a modest amount of urgency here for this be fixed in the next month so we can adopt the latest release. I would submit a PR, but I've not worked in Java since the 1990s.
