### ISSUE TITLE
Question regards to Vulnerabilities

### ISSUE THREAD

**Issue by jaisankar1** [cloudfoundry/uaa#2209]
Hi,

We have upgraded our forked version to UAA 76.5.0. Wondering if you are guys are running SAST or OSA scans to detect vulnerabilities on upstream using checkmarx? If yes can you please provide some insights like what kinds of scans etc? Because our checkmarx scan has detected 400+ SAST vulnerabilities related to the code, also 18 related libraries. I don't see any fixes on the release notes as well except few lib upgrade.
Appreciate your help on this.

**Comment by strehle** [comment]
Hi @jaisankar1 , I recommend that you send the PDF report from checkmarxx to security@cloudfoundry.org . The findings are often in the initial scan, but we will check if there are new issues.
We use Sonar and CodeQL (github) for SAST, see https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent

For library dependency check we have a standard integration into black duck binary and manually Mend, and Github Dependabot is an automatic check for uaa, so on https://github.com/cloudfoundry/uaa/releases/tag/v76.6.0 you see many dep. bumps.

Thanks for your input

**Comment by jaisankar1** [comment]
Thanks Markus for your response. Please find our reports here. 
[OSAVulnerabilities-upstream.pdf](https://github.com/cloudfoundry/uaa/files/10886823/OSAVulnerabilities-upstream.pdf)
[sastreport-uaa-upstream.csv](https://github.com/cloudfoundry/uaa/files/10886824/sastreport-uaa-upstream.csv)

**Comment by strehle** [comment]
Thanks for sharing the information. 
To reported vula: So this is Checkmarxx and we had some of these reports in the past but we do not see any issue. Mostly checkmarxx reports the XSS things. In the past we have fixed some, e.g. https://github.com/cloudfoundry/uaa/commit/40dad6463169b85d07f18be2d21ece13609c9905 . 

To SAST. I created https://github.com/cloudfoundry/uaa/pull/2225 to solve a re-occuring issue about hsql which we use/support only for testing. Woodstox excluded to omit the discussion, because we dont use it. The snakeyaml discussion is available on https://github.com/spring-projects/spring-boot/issues/33457 . UAA relies  on spring and therefore we dont see here an issue. If spring supports snakeyml 2.0 we can proceed with https://github.com/cloudfoundry/uaa/pull/2219 but this is not because of a problem, but simply to satisfy scanners.

My statements are valid for the latest UAA, so of course you need to run always the latest UAA or latest cf-deployment

About the other dependencies in your PDF. There are known as false positives or in case of http client 3.1x, this is because of opensaml2 but known. UAA has codeql and github actions to check if we have problems,. e.g. https://github.com/cloudfoundry/uaa/actions 

Hope this solves your request
