### ISSUE TITLE
Refresh token grant always returns the same refresh token which limits the authorization session

### ISSUE THREAD

**Issue by DarioAmiri** [cloudfoundry/uaa#267]
One of our customers made an interesting discovery:
=== begin quote ===
I created a client with refresh token validity set to 180 seconds and access token validity set to 60 seconds.  The following is what I did and found.
- Get the initial access token and the refresh token using password grant type
- Using the refresh token, get the access token and the refresh token using refresh token grant type
- Then I continually get the access token and the refresh token using the refresh token I got from my previous request/response
- After 180 seconds, I can no longer get the access token and the refresh token using the refresh token

What I found is that the refresh token I get back from each /oauth/token request is the same as the original refresh token.  Refresh token doesn’t refresh with each use.
=== end quote ===

So its seems that every request to UAA for a new access token using refresh token grant returns the same refresh token every time, essentially putting an upper bound on the user session through the client.

We would expect to receive a new refresh token with each refresh token grant and have the capability to revoke the refresh and access token from UAA to explicitly terminate a authorization session.

**Comment by fhanik** [comment]
That is intended behavior. If you get a new refresh token with a new expiration time, the token would never expire. That would warrant a security issue to be filed.

If I misunderstood this issue, please feel free to reopen it. But it sounds like intended behavior. If you get an access token with 1 min expiration and a refresh token with 3 min expiration. The latest you can get a new access token is 3 mins from issuing the original token.

**Comment by sanjeevchopra** [comment]
Filip,
You are right about the token never expiring -  hence the need for token revocation.  

However, along with token revocation a new refresh token will allow authorized application to perform long running tasks on behalf of the user.  This is also useful in mobile, when there is a requirement  for a client on a device to stay logged in for long duration.

**Comment by fhanik** [comment]
@sanjeevchopra 

Token revocation would still not solve the security whole you would create by never expiring a token a refresh token. 

Token revocation is intended for revoking an active token. The expiration time on a refresh token is exactly that. It determines for how long you can refresh tokens for.

**Comment by amiri-ge** [comment]
@fhanik 
As per RFC 7009 token revocation is allowed for both access and refresh tokens.
=== begin quote ===
 This document proposes an additional endpoint for OAuth authorization
   servers, which allows clients to notify the authorization server that
   a previously obtained refresh or access token is no longer needed.
=== end quote ===
Please refer to: https://tools.ietf.org/html/rfc7009 for more details. The key here is that the user needs to be able to revoke access to the client at any time which is not possible if they cannot revoke the refresh token.

As per RFC 6749 concerning refresh token grant:
=== begin quote ===
   The authorization server MAY issue a new refresh token, in which case
   the client MUST discard the old refresh token and replace it with the
   new refresh token.  The authorization server MAY revoke the old
   refresh token after issuing a new refresh token to the client.  If a
   new refresh token is issued, the refresh token scope MUST be
   identical to that of the refresh token included by the client in the
   request.
=== end quote ===

Not issuing a new refresh token per refresh token grant basically defeats the whole purpose of the refresh token. The intent of the refresh token is to let the client keep the authorization session alive in order to enable offline access. In other words, the refresh token is a session of sorts and revoking the refresh token amounts to explicitly closing the session. This is also why refresh tokens are not allowed for implicit grant, because the client id and secret are required to secure the refresh token from abuse.

The best approach is to stagger shorter lived access tokens against much longer lived refresh tokens and allow the revocation of both. This allows the client to keep the session alive so long as there is a certain amount of activity and consent by the user.

**Comment by fhanik** [comment]
@amiri-ge 
We don't implement RFC 7009. We may in the future.

As for RFC 6749, doesn't dictate what "issue a new refresh token" implies other than the scope claim has to be identical. 

If you're reading that it means it should also extend the "living period" for the token, then you're making assumptions not based on the document itself.

It is also a `MAY` which in spec terms means, we leave it to the implementer (usually the spec writers didn't agree on it, and left it open ended).

**Comment by fhanik** [comment]
It is important to understand that a token is user consented. there is nowhere in our system where the user has to option to consent that you may "act on my behalf...**forever**". 

there is very little achieved by adhering to the recommendations here that cannot be achieved by manipulating the time periods for the token periods themselves.

Our tokens are stateless, which is why they are in JWT format. We can revoke tokens on behalf of a user, on behalf of a client or for the entire system by rotating the signing keys. 

We are not able to revoke individual tokens at this time, as a design decision. 

Also, when tokens are in JWT, many resource server for performance reasons prefer to validate tokens locally. In this case, token revocation does nothing for the resource server.

**Comment by amiri-ge** [comment]
@fhanik 
There's alot to address here so let's go though them one by one.
1. You may not implement RFC 7009, but the content of that RFC is indicative of where the OAuth community stands on the topic of token revocation. The information is still useful for making informed decisions.

2. Regarding "MAY" in a spec: It also means that someone is allowed to implement such a feature because it serves a useful purpose - which in this case I'm arguing it does.

3. Regarding your statement of "act on my behalf...forever": This is, in fact, a straw-man argument because I never suggested any such thing. What I did suggest is that one may implement OAuth 2 so that the the user may "allow the client act on my behalf...until I revoke such privileges". This kind of offline access is what our customers are asking for and it is not uncommon for APIs to provide such capabilities.

4. Regarding JWT tokens not being revocable when they are validated locally: This is exactly the reason why a refresh token should not be a JWT token. Instead it should be a long lived token that allows the client to obtain a short-lived JWT token providing the client authenticates successfully. This allows the client to perform offline actions on behalf of the user without encouraging the administrator to configure the authorization server to grant ridiculously long-lived tokens.

Perhaps we can setup a way to talk about this over the phone or in person.

**Comment by fhanik** [comment]
You can always reach out on https://cloudfoundry.slack.com/
I'm in the UAA channel and we can go from there.

**Comment by fhanik** [comment]
>1. You may not implement RFC 7009, but the content of that RFC is indicative of where the OAuth community stands on the topic of token revocation. The information is still useful for making informed decisions.

From previous answer:
We don't implement RFC 7009. **We may in the future.**

>2. Regarding "MAY" in a spec: It also means that someone is allowed to implement such a feature because it serves a useful purpose - which in this case I'm arguing it does.

And in this case, we have valid concerns for the implications of such feature.

>3. Regarding your statement of "act on my behalf...forever": This is, in fact, a straw-man argument because I never suggested any such thing. What I did suggest is that one may implement OAuth 2 so that the the user may "allow the client act on my behalf...until I revoke such privileges". This kind of offline access is what our customers are asking for and it is not uncommon for APIs to provide such capabilities.

Actually, the implication of such an implementation is that "unless we also implement revocation for individual tokens AND user is aware of the revocation feature" the client can act on the user's behalf forever. That's the implication we don't like. We much prefer that you instead have a long lived refresh token that is still time bound. 

> 4. Regarding JWT tokens not being revocable when they are validated locally: This is exactly the reason why a refresh token should not be a JWT token. Instead it should be a long lived token that allows the client to obtain a short-lived JWT token providing the client authenticates successfully. This allows the client to perform offline actions on behalf of the user without encouraging the administrator to configure the authorization server to grant ridiculously long-lived tokens.

Here you state that the refresh token should be long lived. We're ok with that. That is our recommendation for the use case you describe. You also state that there is such a thing as "ridiculously long-lived tokens" 
I'm not sure what the difference between "long lived" and "ridiculously long-lived" is in this case.

What I don't like is the ability to refresh the same access token over and over with no time bounded expiration. 

I think there is an misunderstanding between what the case we see the primary purpose for refresh tokens. For us, just like an access token, a refresh token is time bound. 

A refresh token is only issued at the time we issue the access token. The refresh token can be used to refresh that exact access token, that's it sole purpose. We don't want that purpose to not be time bounded. At some point, the system will say, there is no way you can get that exact access token again until the user approves you to do so. And that happens through a regular access token grant.

The use case described where 

1. a new refresh token is issued AND
2. the new refresh token has an extended expiration time from the original grant

It's bullet 2 that is the issue and comes with the implications.

**Comment by amiri-ge** [comment]
I think a chat protocol will have the same limitations as discussing it in this format. Are you available for a conference call?

**Comment by fhanik** [comment]
hit me up on chat so we can setup the conference call :)
that's where you can always poke me for face to face discussions

**Comment by amiri-ge** [comment]
Still working on getting slack access in the meanwhile...

Let's try this a different way. What our customers are asking is a feature that allows the user to grant access to a client until that access is explicitly revoked. Before we continue any further, we need to agree on whether there is value in implementing this feature.

The current refresh token mechanism has the following weaknesses:
1. The refresh token is essentially a longer lived JWT than the access token. It has the same client id, subject id, scope, and audience of the access token. Which prompts the question: why issue a refresh token at all? Why not just issue a equally long-lived access token?
2. This refresh token, or any token for that matter, is not revocable except by changing the client secret or cycling the signing keys. This is far too onerous a burden for most revocation scenarios.

What I am proposing requires:
1. Issuing a non-JWT one-time use token as a refresh token.
2. Issuing a new non-JWT one-time use token for every invocation of refresh token grant.
3. Providing the ability for the user to revoke that refresh token at any time.

This has the following benefits.
1. You can issue a refresh token that is longer-lived than the access token but that also can't be used by itself to either access a resource server or to obtain information about the user.
2. Interception of the refresh token would not allow an attacker to obtain an access token unless the attacker also had the client id and secret associated with the refresh token. As things are currently, interception of the refresh token is just as good as having the access token.
3. With the help of this refresh token administrators are not encumbered by configuring the authorization server to issue shorter-lived access tokens.
4. If the access tokens are shorter lived and the refresh tokens are immediately revocable you can close the window for attacker mischief after revocation.

**Comment by fhanik** [comment]
@amiri-ge 
Story has been rewritten based on requirements flushed out
https://www.pivotaltracker.com/n/projects/997278/stories/109379332

**Comment by amiri-ge** [comment]
The description looks good. To summarize:
* Individual refresh tokens will have their own expiration to prevent inactive clients from keeping an authorization session open longer than it needs to be. Active clients will have to exchange the current refresh token for another one through refresh token grant at intervals to keep the authorization session open.
* The authorization session itself will have a cap. Once this cap is reached the client will no longer be able to exchange one refresh token for another. The benefit of this cap is that it would protect a user that forgets to revoke client access from inadvertently allowing client access in perpetuity.
* At any time the user can revoke the refresh token and terminate the client's ability to extend access.

**Comment by sumeet-singh04** [comment]
@sreetummidi @fhanik  
Was this resolved ? If yes, which release has this implementation ?
