### ISSUE TITLE
Support reuse of OIDC identity provider configuration jwtClientAuthentication on a global level

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#2752]
### What version of UAA are you running?

77.1.0

### How are you deploying the UAA?

I am deploying the UAA
- using cf-deployment

### What did you do?

Creation of multiple "related" OIDC identity providers in the default identity zones via jwtClientAuthentication. These "related" OIDC identity providers share some of its configuration (e.g. kid). According to the [documentation](https://docs.cloudfoundry.org/api/uaa/version/77.1.0/index.html#oauth-oidc) this configuration has the following sub-parameters:

- kid: UAA 76.18.0 Custom key from your defined keys, defaults to activeKeyId
- iss: Custom issuer, see RFC 7523, defaults to relyingPartyId
- aud: Custom audience, see RFC 7523, defaults to tokenUrl

### What did you expect to see? What goal are you trying to achieve with the UAA?

After the credential rotation for the configured OIDC identity providers, some shared configuration entries require updates. I want to update this shared configuration only once.

### What did you see instead?

After the credential rotation for the configured OIDC identity provider, it is required the shared configuration in multiple identity providers of the default zones.

#### Idea

* Support "central" maintenance of the shared configuration (e.g. kid) for OIDC identity providers in the default zone (via uaa.yml)
* Possibility to reference "centrally" maintained configuration (from jwtClientAuthentication on identity provider level) in the default identity zone

**Comment by strehle** [comment]
I will do first the fix for jwtClientAuthentication  in uaa.yml...

**Comment by peterhaochen47** [comment]
Hi @torsten-sap, I don't think I understand the issue. 

> Creation of OIDC identity providers in multiple identity zones via jwtClientAuthentication and with identical configuration.

Correct me if I'm wrong: So you have multiple identity zones. Each of them is integrated with an external  OIDC provider (are they the same external OIDC provider across different zones? Or different?). Across the zones, the external OIDC provider config's `config.jwtClientAuthentication` field is the same. Correct?

> After the credential rotation for the configured OIDC identity provider, I only want to adapt one configuration to the new credentials...After the credential rotation for the configured OIDC identity provider, it is required to adapt multiple identity providers in different identity zones to the new credentials.

What credential is being rotated in "credential rotation for the configured OIDC identity provider"? What does "adapt one configuration to the new credentials" mean? What configuration? 

Did you mean you wanted to change the value of the `config.jwtClientAuthentication` for each external OIDC provider in each zone? If so, it seems correct to have to update each external OIDC provider config in each zone, one by one? Since the [OIDC provider update endpoint](https://docs.cloudfoundry.org/api/uaa/version/76.31.0/index.html#update) only targets one provider in one zone at a time?

**Comment by torsten-sap** [comment]
@peterhaochen47 

> Correct me if I'm wrong: So you have multiple identity zones. Each of them is integrated with an external OIDC provider (are they the same external OIDC provider across different zones? Or different?). Across the zones, the external OIDC provider config's config.jwtClientAuthentication field is the same. Correct?

Actually I mixed some things up. I updated the issue description.

> What credential is being rotated in "credential rotation for the configured OIDC identity provider"?

It is essentially the key material (private/public key) that changes during credential rotation.

> Did you mean you wanted to change the value of the config.jwtClientAuthentication for each external OIDC provider in each zone? If so, it seems correct to have to update each external OIDC provider config in each zone, one by one?

This is exactly what we want to avoid. The goal is to have only one central key and reference it from the default zone. This way the jwtClientAuthentication configuration/key in the identity zones can stay as is during key rotation and only the central configuration/key needs to be touched.
