### ISSUE TITLE
Angular.js and CORS filter error

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry/uaa#278]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at    
    http://localhost:8080/uaa/oauth/token. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*').

<img width="862" alt="screen shot 2015-12-14 at 6 36 51 pm" src="https://cloud.githubusercontent.com/assets/607429/11815132/92cac5dc-a307-11e5-9897-79b6f2b3aabd.png">

**Comment by fhanik** [comment]
@amiri-ge 

The work around for the above error is to specify `withCredentials: false`
and then it accepts the `*` wild card for the `Access-Control-Allow-Origin` header

That however yields 

    XMLHttpRequest cannot load http://localhost:8080/uaa/oauth/token. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

to take care of this - set the Access-Control-Allow-Headers to the specific headers we allow.
https://github.com/cloudfoundry/uaa/commit/b153573147d32bab579717d56f25c0f38474dc98

**Comment by fhanik** [comment]
This value should not be hard coded.

If the origin is allowed, we should send it back spelled out

https://github.com/cloudfoundry/uaa/blob/b153573147d32bab579717d56f25c0f38474dc98/common/src/main/java/org/cloudfoundry/identity/uaa/web/CorsFilter.java#L158-L158

**Comment by amiri-ge** [comment]
@fhanik Agreed. FWIW that's particular bit of code is left over from the original CorsFilter code before I touched it.

**Comment by fhanik** [comment]
@amiri-ge 

I'm reworking this filter right now based on reading up on CORS. The current filter has completely different implementation if the request is XHR vs the request is non XHR. 

Why is that?

**Comment by amiri-ge** [comment]
@fhanik Originally, before I ever touched it, this filter was extremely naive in its implementation. It simply passed a wildcard for Access-Control-Allow-Origin and left all the other headers pretty wide open (see https://github.com/cloudfoundry/uaa/blob/139e57ee75a5cdb877e8bb8a1975196213a20711/common/src/main/java/org/cloudfoundry/identity/uaa/web/CorsFilter.java).

Our teams were running into problems with this implementation of the filter because it would not work when the browser was including the "X-Requested-With" header during XHR requests. I had to build logic that allowed CORS during XHR requests but I thought it would be irresponsible to use the same wide-open policy that the existing CORS filter was using.

I tried looking for an existing Spring CORS filter but there was nothing compatible with the version of Spring UAA was using at that time. So I decided to build my own CORS filter but to make it restrict the allowed origins, methods, and uris for CORS with XHR. The intent was to the risk of allowing CORS with XHR as much as possible.

At the same time, I didn't want to disturb any of the existing functionality. Thus you have a filter that preserves the existing functionality of the CORS filter except when handing an XHR.

**Comment by fhanik** [comment]
Thanks @amiri-ge I'll ping you when I have a working version, and would greatly appreciate it if you could review it.

**Comment by amiri-ge** [comment]
@fhanik sure thing.

**Comment by fhanik** [comment]
@amiri-ge 

Commit https://github.com/cloudfoundry/uaa/compare/0ba64a14038e...d0bd3981d564

It really only does two things

1. It treats the XHR and non XHR requests the same way
2. It allows different config for XHR vs non XHR

**Comment by amiri-ge** [comment]
@fhanik I reviewed the code but, unfortunately, I don't have the ability to add line level comments. There are many changes but I overall they look pretty good. I like that the code is reused as much as possible for XHR vs non XHR. I had a few nitpicks/suggestions:

1. "logger" is both static and final. I believe the standard Java convention is to name such members in all caps so they are easier to spot in the code.
2. I noticed there are methods for assembling and splitting comma separated strings to lists as well as a method called "containsIngoreCase". You might want to consider using StringUtils.join(), StringUtils.split(), and StringUtils.containsIgnoreCase() from Apache Commons Lang, which I believe is already in the list of dependent libraries for UAA. No need to reinvent the wheel.

**Comment by fhanik** [comment]
Thanks @amiri-ge 

I'm mainly looking for functional feedback, meaning, if you have Javascript clients that perform CORS requests, if you could test those and ensure that they still pass through.

thanks
Filip

**Comment by amiri-ge** [comment]
@fhanik That will be difficult. Besides the unit tests that I originally wrote for the features, we don't have any other automated testing for this feature. Additionally, the teams that rely on this feature won't be able to test it until we deploy it for them which will not be anytime soon. On top of that it's the holidays so there are not too many people around.

**Comment by fhanik** [comment]
Closing via https://github.com/cloudfoundry/uaa/commit/4633e0f0e68db39771420738cd677e50fc8455bc

a configured cors filter will return the correct origin and not `*` when `corsXhrAllowedCredentials` or `corsAllowedCredentials` are set.
