### ISSUE TITLE
support url of utf-8 encoding

### ISSUE THREAD

**Issue by coolxv** [cloudfoundry/uaa#295]
##add to web.xml    
```xml
    <filter>
        <filter-name>encodingFilter</filter-name>
        <filter-class>
            org.springframework.web.filter.CharacterEncodingFilter
        </filter-class>
        <init-param>
            <param-name>encoding</param-name>
            <param-value>utf-8</param-value>
        </init-param>
        <init-param>
            <param-name>forceEncoding</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>encodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```

**Comment by fhanik** [comment]
Can you give us a bit more context around the issue that you are facing. It will help us add a test case before we add the configuration change.

**Comment by coolxv** [comment]
request url  for /Users?filter=username sw "莉莉" . url contains chinese( encoding utf-8).

**Comment by georgi-lozev** [comment]
Hi,

I'm facing a problem with cf login, which from my point of view is related to this one and can give you more context.

When I try to log in with cf cli with a pass that contains UTF-8 character, like `paßword` for example, the client is making a POST with the following url-encoded content `grant_type=password&password=pa%C3%9Fword&scope=&username=username` Here the ß character is UTF-8 escaped as `%C3%9F`.

However later in the [extractCredentials](https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/authentication/BackwardsCompatibleTokenEndpointAuthenticationFilter.java#L199) it is decoded with [tomcat's default ISO-8859-1](http://wiki.apache.org/tomcat/FAQ/CharacterEncoding#Q3) and the string becomes something like `pa\xC3\x83\xC2\x9Fword`. This forces everyone in the chain that follows, like LDAP, to first encode it to ISO-8859-1 and then back to UTF-8 in order to get the original string that was sent. 


I was able to fix it on my environment by following the recommendations provided [here](http://wiki.apache.org/tomcat/FAQ/CharacterEncoding#Q8), but I think it would be good if we have it in UTF-8 by default.

**Comment by fhanik** [comment]
can you rerun the command with `CF_TRACE=true`

does the client set the correct encoding header?

**Comment by georgi-lozev** [comment]
```bash
Email> ußername

Password>
Authenticating...

REQUEST: [2016-03-27T19:17:25+03:00]
POST /oauth/token HTTP/1.1
Host: login.bosh-lite.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.15.0+fa1bfe2 / darwin

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=u%C3%9Fername
```

Here I added the UTF character inside the username, because the password is hidden, but it's escaped in the same way.

There is also an open [issue](https://github.com/cloudfoundry/cli/issues/560) in cf-cli, but as far I can see it's more related to the uaa way of dealing with encodings.

**Comment by fhanik** [comment]
We believe this was fixed through [another story](https://www.pivotaltracker.com/story/show/119024343)

https://github.com/cloudfoundry/uaa/commit/eec8d30f480b8e3874aac375cd3ec04811f69c80

You can also view a similar issued filed with [Cloud Foundry CLI](https://github.com/cloudfoundry/cli/issues/560)
