### ISSUE TITLE
BasicAuthenticationFilter.doFilter() method taking too long in load testing

### ISSUE THREAD

**Issue by sivabalans** [cloudfoundry/uaa#296]
I am performance testing UAA version 2.7.3. I am testing 2 workflows with 50 jmeter threads.
1. Get a new Oauth token with grant_type=password - /TokenEndpoint/postAccessToken
2. Check token to see if it is valid. - /check_token
In both of these calls, I notice that BasicAuthenticationFilter.doFilter() method is consistently taking 100ms which seem to be quite high. I have about 1000 test client and users which I loop through in my test to get the token and also to check the token. See below for some New Relic data during the test run:
/TokenEndpoint/postAccessToken:
![image](https://cloud.githubusercontent.com/assets/10453642/12362740/d134b99c-bb79-11e5-8f5d-68e4d476f0ae.png)
/check_token:
![image](https://cloud.githubusercontent.com/assets/10453642/12362755/e5c84216-bb79-11e5-8638-e8246d5e6abe.png)

Now when I switch using just one client and one user(marissa), I dont even see that method in the New Relic graph which goes to show that the time taken is negligible. 
See below for graphs with just 1 user 
/TokenEndpoint/postAccessToken:
![image](https://cloud.githubusercontent.com/assets/10453642/12362911/ace035fc-bb7a-11e5-9fd8-d5e9eec7c5c0.png)
/check_token:
![image](https://cloud.githubusercontent.com/assets/10453642/12362926/c4a2b32c-bb7a-11e5-9d17-81738de8b682.png)

Any idea what is making that method expensive when running with multiple users and clients and is there a way to work around it?

**Comment by fhanik** [comment]
Yes, we use bcrypt to encrypt user passwords in the database. 
This algorithm is intentionally designed to be slow to prevent brute force guesses of passwords to eventually come true.

We do have a cache put in place for client secrets, so that endpoints that require client secrets, like refreshing a token or getting a token from an authorization_code grant, should go faster.
(or check_token should go faster for the same set of clients)

We don't cache this for users, and the idea is that for a single user, you should not be doing many requests per second, after all, access token are quite long lived.

So as part of this story, I'd like to investigate why /check_token that only requires client credentials is slow. That should definitely improve.

**Comment by fhanik** [comment]
Closed. Behavior is as expected.
