### ISSUE TITLE
Improve documentation on configuring clients to revoke tokens

### ISSUE THREAD

**Issue by ferfei** [cloudfoundry/uaa#332]
Hi,
it seems that revoke token endpoint requires uaa.admin scope but a regular user should be able to revoke their own token, we are using a password flow with UAA and implementing logout functionality we were not able to access the revoke token endpoint ( we had a work around to get a admin token using client_credential but we don't think this is the right way to do it)
any advice?

**Comment by fhanik** [comment]
It is possible, as long as the user AND client both have the `tokens.revoke` scope

https://github.com/cloudfoundry/uaa/blob/0d24f57b6b9aac45f6f99b6df3388a5e4060dd25/uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml#L58-L58

**Comment by jchesterpivotal** [comment]
We got bitten by this too. It's a frustrating experience for non-experts.

It seems to me that we did not understand:

1. That we needed to know in advance that we needed both clients and tokens with `tokens.revoke` scope, or
1. How we get out of this situation once we're stuck in it.

We don't have any clients with `uaa.admin` or `tokens.revoke`, nor any tokens with `tokens.revoke`. We're stuck with an unrevokable token,  even though we have the credentials of the client which created it.

Many apps relying on UAA are from teams who rightly do not have `uaa.admin` scopes, but who have clients issuing sensitive and valuable tokens. When these leak, it should be possible to revoke them immediately, without delay and without needing to coordinate with another team. But apparently it isn't, unless you knew the correct setup in advance.

What makes this frustrating is that while this is all clear in retrospect, it wasn't clear ahead of time. The necessity of the `uaa.admin` or `tokens.revoke` scopes is only discussed in a comment in tables of endpoints (`/oauth/token/revoke/ *`). In tables discussing HTTP headers. That's where we could have learned about necessary scopes that we needed to set at creation time. 

A comment in freeform text in a table about HTTP headers does not strike me as a first place to look for scopes I didn't know I needed to look for. An added column in those tables with scopes would help, but not much. A highlighted discussion or warning would help more.

The remark in one such table comment that "You can use any token with matching token ID to revoke itself" is confusing and misleading, since this doesn't appear to be the case at all.

Importantly, we do not see this topic being discussed in the guide to token *creation*, which is the one point at which we could have set it up correctly.

Our suggestion is that, at a minimum, the documentation is updated in both the creation and revocation sections to emphasise how to avoid being painted into a potentially dangerous corner. 

But we would much rather be able to revoke our own tokens.

**Comment by fhanik** [comment]
Documentation for 
https://docs.cloudfoundry.org/api/uaa/version/4.6.0/index.html#revoke-a-single-token

states

    Authorization | Bearer token with uaa.admin or tokens.revoke scope. 
    You can use any token with matching token ID to revoke itself.

I guess we need to improve this message here so that the **or** in between the sentences is clearer.

**Comment by kopptr** [comment]
I don't think the "or" in between the sentences is correct. Attempting to revoke a refresh token with the JTI claim, but without either of those scopes, fails with a 403 response:

```
http DELETE https://[our UAA server]/oauth/token/revoke/[redacted jti]   Authorization:'Bearer [redacted full token]'
HTTP/1.1 403 Forbidden
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Connection: keep-alive
Content-Length: 123
Content-Type: application/json;charset=UTF-8
Date: Mon, 18 Sep 2017 19:48:16 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Www-Authenticate: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="uaa.admin tokens.revoke"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 2b1eee7b-f790-4692-4aa2-e124e89f1030
X-Xss-Protection: 1; mode=block

{
    "error": "insufficient_scope",
    "error_description": "Insufficient scope for this resource",
    "scope": "uaa.admin tokens.revoke"
}
```

We tried this with each client we have, and also tried it using `uaac curl`, and got similar results. It seems like one cannot use any token with matching token ID to revoke itself.

**Comment by jhamon** [comment]
@fhanik I think the problem being described here is that the knowledge that the scope `tokens.revoke` is required to revoke tokens issued with `format=opaque` is very far removed (both in space in the documentation and in time) from the point where the client was created and decisions about what scopes the client should request were made. Our API docs leave this landmine open for people because the decision about whether to use revocable tokens or not does not live in the client registration but is part of the `/oauth/token` query params. As a result, it's very easy to make a client that fetches revocable tokens but has no way to revoke them later without getting a uaa.admin to update the client configuration first.

This doesn't seem like something that can be easily addressed through the API docs. But it might be a candidate for some kind of more specific conceptual setup & best practices guide for app developers interested in using and understanding revocable tokens.

**Comment by fhanik** [comment]
@jhamon @kopptr 

> it's very easy to make a client that fetches revocable tokens but has no way to revoke them later without getting a uaa.admin to update the client configuration first.

I'm confused. I would say you are both wrong or misunderstanding the documentation.

The documentation shows that you can use format=opaque in the example

    curl 'http://localhost/oauth/token/revoke/29ef79f017d0429c8f0ccbbe0b4afaf2' -i -X DELETE \
    -H 'Authorization: Bearer cc42c0a963354f9e8742e38b50cf97a2'

The token used has only `openid` nothing else

https://github.com/cloudfoundry/uaa/blob/8215e9a0c3eadcc0124e91096050926407efd314/uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java#L739

I realize that the above test uses a token with `uaa.admin`. But the test passes if I change that to the token itself to align it with the documentation

    getMockMvc().perform(delete
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + userInfoToken))
                .andExpect(status().isOk())
                .andDo(document("{ClassName}/{methodName}", preprocessResponse(prettyPrint()), requestHeaders, pathParameters));

**Notably**

    .header(HttpHeaders.AUTHORIZATION, "Bearer " + userInfoToken))

**Comment by jhamon** [comment]
I was restating my understanding of @jchesterpivotal's complaint, but it seems that it is possible to revoke tokens without having the `tokens.revoke` or `uaa.admin` scopes on your client. I just did a quick trial and was able to revoke a token without these scopes on my client. It requires them have knowledge of the token and jti, which they may not be holding on to.

**Comment by fhanik** [comment]
@jhamon @jchesterpivotal 

I'm pretty sure that you can also invoke 

   /oauth/token/revoke/client/my-client-id

using *any* token issued to my-client-id without needing privileged scopes.

**Comment by aeijdenberg** [comment]
Why is this closed? The docs (http://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#revoke-a-single-token) continue to state that `You can use any token with matching token ID to revoke itself.`, when this is still not true.

Note the refresh token that I'm trying to revoke is of format JWT - perhaps the clarity needed is that these are not revocable at all?

**Comment by davipc** [comment]
@aeijdenberg I'm still seeing the same behaviour as well... I can revoke access tokens acquired using refresh tokens and the _refresh_token_ grant type, but I cannot revoke the refresh token itself.
