### ISSUE TITLE
SAML Identity providers in uaa zone deactivated after restart

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/uaa#344]
When adding a SAML identity provider using the REST api in the uaa identity zone, the identity provider gets deactivated after a restart of the UAA. The logic seems to be to match the identity providers against the uaa.yml/login.yml configuration files.
As  identity providers added through the REST API are not present in the configuration file, they get deactivated.

This happens in IdentityProviderBootstrap.afterPropertiesSet:
```
@Override
    public void afterPropertiesSet() throws Exception {

        providers.clear();
        addLdapProvider();
        addSamlProviders();
        addKeystoneProvider();

        String zoneId = IdentityZone.getUaa().getId();

        //deactivate all providers that are no longer present
        deactivateUnusedProviders(zoneId);
```

I suggest to enhance the IdentityProvider class & corresponding table by an additional column to identify if the configuration was added by REST api or by configuration files. Only identity providers added from the configuration should be desctivated if not present anymore.
We can create a pull request for that in the develop branch.

Best Regards,

Martijn de Boer

**Comment by fhanik** [comment]
That is expected behavior. Configuration of the default zone is made by the configuration files only.

Imagine this scenario

1. you add a IDP to config file
2. Start the UAA
3. You remove the IDP from the config file
4. Restart the UAA

This should deactivate any providers not in the configuration file. This is how the system works. The configuration files configure the default zone, and the API the non default zones.

A pull request with test cases is always welcome!

**Comment by mwdb** [comment]
I agree with you that the default zone allows configuration through configuration files and also that when identity providers are removed from the configuration files are the should be deactivated.

I did not yet understand the reason why IdPs should not be configured through the REST API in the default identity zone. One implementation option would be to store if an IdP was added by REST API or through configuration files and only deactivate it when it was added through the configuration file and removed at a later point in time.
