### ISSUE TITLE
Check Token scope(s) doc is inaccurate

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/uaa#368]
In [Check Token][1] API docs the `scopes` request parameter is described as:

```
scopes	Array	Optional	Comma-separated string of scopes to check if scopes are present on the token
```

whereas the apparent type on the examples is `String`. The description could say something like: _String of comma-separated scopes ..._.

Furthermore the response field `scope` is described as:

```
scope	Array	Comma-delimited list of scopes authorized by the user for this client
``` 

and it _is_ an array (or a Json list, at least), but the doc shouldn't really say "comma-delimited" (nor "comma-separated"), because that is a feature of the Json representation and not of the field value.

[1]: http://docs.cloudfoundry.com/uaa/#check-token

**Comment by plfx** [comment]
@Zteve Thank you for pointing out these issues in our documentation. We will address the JSON field being erroneously described as "comma-delimited"; that's an error on our part.

As for the query parameter, I can understand how the type maybe be confusing, but the issue stems from the fact that request parameters really have no type, as far as HTTP is concerned; they are all "strings". Our documentation is making a mild abuse of the term "type" in order to clarify what the content of this string should be, even though these types have no rigorously-defined meaning as far as request parameters go.

We do not intend the `Array` type to imply that request parameters should be set off with [square brackets], just as we don't intend that the `String` type should imply the parameter value needs to be surrounded with "quotes". In the context of this abuse, I believe "comma-separated string of scopes" is just as strongly disambiguating as "string of comma-separated scopes".

I am marking this issue as closed, and you should see the documentation fixed very shortly. If you find other issues with typing or description in our documentation, please continue to inform us. Thank you.

**Comment by Zteve** [comment]
Thank you Jeremy for explaining the rationale well.
