### ISSUE TITLE
Sample doesn't match doc for Create User

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#375]
The documentation for Create User (http://docs.cloudfoundry.com/uaa/#create48) doesn't match the sample input in the documentation. The following fields appear in the sample, but not in the doc:

meta.version
meta.created
name.formatted
schemas

It seems unlikely that the user should be setting meta (it's up to the system to decide when a user was created, not the requestor, for audit reasons).
The formatted name field is reasonable, but not consistent with (for example) list users.
I don't understand uaa enough to know whether schemas is appropriate here.

**Comment by fhanik** [comment]
The schemas and meta fields come from the early SCIM specification
http://www.simplecloud.info/specs/draft-scim-core-schema-00.html

Those fields are not required, they are being sent up in the sample, because the Java object that represents the data model simply sends it up. It's completely ignored on the server.
