### ISSUE TITLE
Cannot add user to group if group is not in `uua.scim.users`

### ISSUE THREAD

**Issue by thausler786** [cloudfoundry/uaa#423]
## Issue

When I create a user and try to grant them `cloud_controller.admin_read_only` scope through the uaac, I can only do so if the `cloud_controller.admin_read_only` scope is in the `uua.scim.users` section of my cf manifest.

If I deploy cf with `cloud_controller.admin_read_only` in the `uua.scim.users`and later remove it, I am still able to add the user to the `cloud_controller.admin_read_only` group.

I expect that when `cloud_controller.admin_read_only` appears in one of the `uaa.client`'s scopes, I should be able to create a user with this scope.  It should not have to also appear in the `uaa.scim.users` section.

## Context

We are working on manifest generation to enable cf admins to add `cloud_controller.admin_read_only` scope to cf users.

We previously talked about being unable to create a `cloud_controller.admin_read_only` when it is not in `uaa.scim.users` user during an interrupt, but failed to reproduce it for you at that time because once `cloud_controller.admin_read_only` is included in the `uaa.scim.users` section once creating an `admin_read_only` user always succeeds.

## Steps to Reproduce

1. Generate a manifest for Cloud Foundry.  `cloud_controller.admin_read_only` should be in `uaa.clients.cf.scopes`.
1. Deploy Cloud Foundry
1. Follow the steps on this guide to add a user to the `cloud_controller.admin_read_only` group:  https://docs.cloudfoundry.org/adminguide/uaa-user-management.html

Specifically, follow the steps for 'Add an Admin User' but add an `cloud_controller.admin_read_only` user instead.

## Expected result

When `cloud_controller.admin_read_only` appears in one of the client's scopes, I should be able to create a user with this scope and receive:

`success`

## Current result

`CF::UAA::NotFound: CF::UAA::NotFound`

**Comment by plfx** [comment]
@thausler786 Hi Tim.

  The reason you're receiving the `NotFound` is because the group `cloud_controller.admin_read_only` does not initially exist. However, when you add it to `uaa.scim.users`, the UAA creates it at the time of start-up so that the users can be added to it.

The proper why to accomplish this (so that users do not get automatically added to it), is to create the group by adding it to `uaa.scim.groups` in the manifest, where you can also specify a human-readable description which will appear on the approval page for the user.

I am closing this issue. If the issue does not go away or the solution seems to have other implications, please do open another.
