### ISSUE TITLE
Support PKCE (Proof Key for Code Exchange)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/uaa#455]
As part of using UAA for mobile SSO use-cases (see https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03), the ability to [protect authorization codes](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03#section-8.2) relies on Proof Key for Code Exchange (PKCE) support specified in https://tools.ietf.org/html/rfc7636

The [UAA api](http://docs.cloudfoundry.org/api/uaa/) does not seem to yet support the related `code_challenge` endpoint parameters of PKCE as an example.

Is there anything planned to support PKCE in the future ?

**Comment by sreetummidi** [comment]
No plans to implement this at this time.

**Comment by markmabe** [comment]
@sreetummidi Hi is there a reason there are no plans to implement PKCE in UAA?

**Comment by minyangu** [comment]
@sreetummidi 
Hi, same question, why UAA has no plan to implement the PKCE for mobile apps? 

Please also note this:
The OAuth 2.0 Security Best Current Practice document recommends **against using the Implicit flow entirely**, and OAuth 2.0 for **Browser-Based Apps** describes the technique of using the **authorization code flow with PKCE**.

Although this is still under draft status, this may soon become a confirmed standard by IETF so that browser-based apps like SPA are also required to use the Auth Code + PKCE flow mechanism.

**Comment by SHRIVP** [comment]
@sreetummidi ,

Does UAA support PKCE now?
