### ISSUE TITLE
/check_token endpoint can be optimized as far as indexing and number of SQL queries

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#463]
We noticed that some of the SQL queries get called as part of /check_token endpoint taking ~ 200 ms. per query and probably can be indexed based on search field and hopefully also number of SQL calls per transaction (especially repetitive calls) can be reduced. Now it is about 30 SQL queries per transaction.
![screen shot 2016-10-11 at 4 44 10 pm](https://cloud.githubusercontent.com/assets/11415583/19292934/acedf960-8fd4-11e6-93d5-7bf8a405280f.png)
![screen shot 2016-10-11 at 4 44 36 pm](https://cloud.githubusercontent.com/assets/11415583/19292937/b3041104-8fd4-11e6-91b8-0533084b8097.png)
![screen shot 2016-10-11 at 4 44 58 pm](https://cloud.githubusercontent.com/assets/11415583/19292940/b7f9019c-8fd4-11e6-9e95-89e3b769c9f8.png)

**Comment by mwdb** [comment]
We identified the same issue.
Since UAA version 3.X is supporting nested groups. This causes the number of SQL statements to the group_membership table to grow with the numbers of scopes assigned.

We have scenarios where 100 scopes are assigned to a user. During issuing of a token, the JdbcUaaUserDatabase.getUserById is called multiple times. For every call, it:
1) reads information from the user table
2) reads the 100 scopes with one SQL statement from the group,group_membership table
3) For each of the 100 groups, makes a new call to the DB to check if nested groups exist.

This issue is 3), which was introduced with the nested groups. 
We'll make a contribution to optimize 3 by querying multiple groups memberships in one query.

This brings down the number of DB queries for a user with 100 scopes from 102 to 3.
 JdbcUaaUserDatabase.getUserById

We're working on contributing this change.

**Comment by mwdb** [comment]
See PR https://github.com/cloudfoundry/uaa/pull/471
