### ISSUE TITLE
Do all CF components use online token validation? 

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#478]
On our CloudFoundry installations, we have the policy that whenever a user leaves the company, we have to disable his access to the system within a short amount of time (i.e. 30 minutes).

We ensure this by deleting the user from the UAA. But since there might be still valid tokens around, the user might interact with CF components until the tokens expire. If the CF component does online validation (using `check_token`), it would detect that the user does not exist anymore and prevent access. But if the CF component does not contact the UAA for the check (offline validation) it would not notice the user deletion.

Do you know if every CF component that acts as a OAuth2 RP (not only API, but also doppler, ssh-proxy, diego) does online token validation using `/check_token`?
The goal for us is to verify that we can block access to CF completely by deleting the user. 

I ask here as the UAA team might know about the big picture of CF Auth.  Would this question be asked better on the CF mailing list?

**Comment by d** [comment]
0. You are right, this is the wrong place to ask that question. vcap-dev mailing list is probably the right place.
0. IIRC the default (or even possibly the only) configuration on most components do offline validation, meaning that they only validate the cryptographic integrity of the token. One remedy for your company though, is that you can make sure your token validity is no longer than your "access termination SLA", say 30 minutes. Because the user will need to refresh every 30 minutes at the UAA, and that will be sufficient to shut him or her out of the system if you have revoked his access to UAA.

**Comment by ematpl** [comment]
@d The [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/) is currently the principal mailing list for Cloud Foundry discussion. vcap-dev was deprecated quite some time ago because of limitations on Google Groups.

Thanks,
Eric

**Comment by MatthiasWinzeler** [comment]
Thanks for your help! I glanced at the codebases of the components and figured that while loggregator uses `check_token`, ssh proxy anyway hits the UAA during auth (and thus would be fine), at least the cloud controller uses offline validation.

So we'll not rely on this and shorten the access token lifetime appropriately.
