### ISSUE TITLE
Remember Me

### ISSUE THREAD

**Issue by scizeron** [cloudfoundry/uaa#488]
Hi,
Acting as a authentication provider, why UAA doesn't provide the  "remember Me" feature ?
When submitting the login form, when  selecting a IDP link (2 links per idp or add a intermediate check step) ... 
It doesn't seem to be a big deal as all is based on spring-security.

**Comment by sreetummidi** [comment]
Please enable the Account Chooser & IDP Discovery to enable this function. This is supported from UAA 3.9.0
This is set on the Identity Zone. 

http://docs.cloudfoundry.org/api/uaa/index.html#updating-an-identity-zone

```
config.idpDiscoveryEnabled	Boolean	IDP Discovery should be set to true if you have configured more than one identity provider for UAA. The discovery relies on email domain being set for each additional provider
config.accountChooserEnabled	Boolean	This flag is required to enable account choosing functionality for IDP discovery page.
```

**Comment by kkdatkiran** [comment]
@sreetummidi I don't understand how "Remember Me" functionality works for user logins and all, can you please let me know if there is a "Remember Me" functionality?

**Comment by strehle** [comment]
currently no "Remeber me" Option, but meaningful to us
@torsten-sap  FYI

**Comment by bruce-ricard** [comment]
Looking at this issue, I don't fully understand which feature it's asking for. Could you please try to quickly elaborate @strehle please?

**Comment by strehle** [comment]
if you look to initial request it suggest spring security

So for me it is simply similar to 
https://www.codejava.net/frameworks/spring-boot/spring-security-remember-me-examples
or
https://www.baeldung.com/spring-security-remember-me

UAA has a cookie with long lifetime, e.g.
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/login/CurrentUserCookieFactory.java

But with remember me the information about the login would be in the cookie, similar to the refresh token for the oauth flows and if you open the browser you can re-use this to re-login again without your credentials.
I know that browsers offer a similar password store but here UAA should encrypt the cookie so that you cannot readout the password from browser again.

**Comment by bruce-ricard** [comment]
I'm closing it as it's been stale for over a year, one could argue 5 years.

Feel free to reopen if you really care about this feature.
