### ISSUE TITLE
The gradlew run stuck at "Building 97% >: cargoRunLocal"

### ISSUE THREAD

**Issue by alfredcs** [cloudfoundry/uaa#504]
Here are the errors. Others had reported same issue but not resolution. Any suggestions? Thx!

:cloudfoundry-identity-samples:cloudfoundry-identity-app:assemble
:cloudfoundry-identity-samples:cloudfoundry-identity-app:assemble took 0ms
:assemble
:assemble took 0ms
:cleanCargoConfDir UP-TO-DATE
:cleanCargoConfDir took 0ms
> Building 97% > :cargoRunLocal

:cargoRunLocal
Press Ctrl-C to stop the container...
> Building 97% > :cargoRunLocal 
------------------------------
# curl -H "Accept: application/json" localhost:8080/uaa/login
FAILURE

**Comment by fhanik** [comment]
It's not stuck. This happened

1. Tomcat started
2. Tomcat tried to start the UAA web app
3. The UAA web app tried to start based on configuration
4. Configuration is incorrect, failure to start

Ctrl+C will kill the process.

Your error will be in `uaa/build/reports/tests/uaa-server.log`

My guess is you're missing required configurations. If you switch to the develop branch, we added these back during cargo run

This was fixed in this commit
https://github.com/cloudfoundry/uaa/commit/c68fba71e7c266f2e9d1d2a3041dc2e0efa32a07
