### ISSUE TITLE
Saml update metadata not working

### ISSUE THREAD

**Issue by bondugula** [cloudfoundry/uaa#522]
We are having an intermittent saml issue, we see the following error "org.opensaml.common.SAMLException: Response doesn't have any valid assertion which would pass subject validation" , underlying exception is "SAMLProcessingFilter: Caused by: org.opensaml.xml.validation.ValidationException: Signature is not trusted or invalid". The interesting part is that the metadata for the idp is outdated, the certs were changed on the idp side recently and there was never a metadata update in UAA. However some requests are still passing and it fails intermittently instead of always. In this case we have multiple instances of UAA and multiple identity zones configured to use the same external idp.

**Steps to reproduce in isolation:**

We have a sample app, and one instance of UAA deployed in Cloud foundry. We configured the app to use an external identity provider. Our sample app was working fine and then we updated the idp metadata with incorrect certs. And still the app continued to work fine. We restarted UAA and then our sample app started failing. We then updated the idp metadata with the correct certs and still our app was failing until we restarted the UAA again. 

When we get the idp config between these steps, the idp metadata is up to date. There seems to be some sort of cache based on what we observed.

**Comment by sanjeevchopra** [comment]
A bit clarification - when there is intermittent failures on the sample app @bondugula  is referring to,  there are other identity zones in the uaa which do have the correct metadata. 

@fhanik  this is the same issue we had discussed over slack - except we incorrectly concluded that a restart fixes the issue. This was because I didnt realize that the correct metadata/key was being picked from a global cache benefiting from correct metadata from a different identity zone.

The cache you had identified is in `org.opensaml.security.MetadataCredentialResolver`.

**Comment by 6palace** [comment]
To further clarify if needed, the sample app, when pointed to the main UAA, should always be failing because we corrupted its metadata. The intermittent failures are more specifically intermittent successes caused by the cache presumably using correct credentials from other zones.

**Comment by sreetummidi** [comment]
This issue has been addressed .
