### ISSUE TITLE
Don't invalidate invite code after first view

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/uaa#587]
We'd like to use [invites](https://docs.cloudfoundry.org/api/uaa/#force-user-password-to-expire) as a way of creating accounts for users. However we anticipate a couple of problems related to invitations expiring after the first time they're viewed:

1. Some email systems automatically check links in emails for malicious content. This means the invitation would be invalidated before the user has a chance to access it.
1. Some people will click on the link before they are ready to complete the form and will mark the email as unread to come back to later. This means the invitation would be invalid when the user goes back to complete it.

Could this behaviour be changed?

Here are some options that we thought of from our understanding of the code:

1. Make `/invitations/accept` retrieve and check the code without deleting it. It would then be deleted by `/invitations/accept.do` when the form is submitted. This would require a change to the `ExpiringCodeStore` interface.
1. Make `/invitations/accept` call `setCode()` and `setExpiresAt()` on the new code passed to `/invitations/accept.do` so that matches the previous code and doesn't expire the invite if the form isn't submitted.

We'd appreciate your feedback. Thanks!

**Comment by bleach** [comment]
I just thought I'd check in on this one, because we're still finding that this trips people up regularly, particularly scenario 2; people clicking on an invite link, not finishing the signup and then coming back later and being told the invite has expired.

Is there any way around this currently? Would you accept a PR to amend the behaviour as described previously by @dcarley?

**Comment by sreetummidi** [comment]
Will be addressed with https://www.pivotaltracker.com/story/show/152524314
