### ISSUE TITLE
credlew hanged-up on Building 97% > :cargoRunLocal

### ISSUE THREAD

**Issue by PavelSosin** [cloudfoundry/uaa#677]
credlew run hanged-up on windows 10 with Java 8 and Tomcat 8 like in issue #504 
Log tail:
Deploying [C:\Users\i016373\uaa\samples\api\build\libs\cloudfoundry-identity-api-4.5.0.war] to [C:\Users\i016373\AppData\Local\Temp\cargo\conf/webapps]...
Deploying [C:\Users\i016373\uaa\samples\app\build\libs\cloudfoundry-identity-app-4.5.0.war] to [C:\Users\i016373\AppData\Local\Temp\cargo\conf/webapps]...
Deploying [C:\Users\i016373\uaa\uaa\build\libs\cloudfoundry-identity-uaa-4.5.0.war] to [C:\Users\i016373\AppData\Local\Temp\cargo\conf/webapps]...
Tomcat 8.x started on port [8080]
[ant:cargo] Press Ctrl-C to stop the container...
Press Ctrl-C to stop the container...
> Building 97% > :cargoRunLocal

http:/localhost:8080/uaa responses with "FAILURE" with log:
[localhost_access_log..2017-08-09.txt](https://github.com/cloudfoundry/uaa/files/1212214/localhost_access_log.2017-08-09.txt)
[uaa - log.txt](https://github.com/cloudfoundry/uaa/files/1212225/uaa.-.log.txt)

**## ... end, after deployment of uaa to my trial cf space I got very similar stack dump!**

**Comment by jhamon** [comment]
From the log it looks like you have not configured a private key in your `uaa.yml` file for the property `login.serviceProviderKey`.

**Comment by shradhasa** [comment]
Hi, i am also getting same error. How do we configure property login.serviceProviderKey. isn't it already configured?

**Comment by jhamon** [comment]
@shradhasa No, it is not configured out of the box. You must supply a key. If you are running the UAA as a standalone Java app, you need to set the key in the `uaa.yml` file. If you're deploying the bosh release of uaa, you will set a value under `login.saml.keys` in your bosh manifest. These configurations are required because the UAA acts as a SAML Service Provider and they must be set by the operator because the values are secret and should not be reused across deployments.

Here are some instructions for how to configure these
https://github.com/cloudfoundry/uaa-release#configuring-required-properties-for-uaa-start-up
