### ISSUE TITLE
UAA check_token is not working with spring-security-oauth2 since 2.1.0.RELEASE

### ISSUE THREAD

**Issue by migger** [cloudfoundry/uaa#716]
### What version of UAA are you running?

uaa-4.5.0

### How are you deploying the UAA?

I am deploying the UAA

- using cf-release
- using cf-deployment

### What did you do?

We have created a microservice with @EnableResourceServer annotation on main spring boot class. the service is using spring-security-oauth2:2.2.0.RELEASE as sub-dependency of 

org.springframework.cloud:spring-cloud-starter-oauth2:2.0.0.M1

Then we've got correct token from /oauth/token endpoint.
And we pass the token to the http request as Bearer authorization

### What did you expect to see? What goal are you trying to achieve with the UAA?
Since the token is valid we expect to see 200 response but we didn't

### What did you see instead?

We got non-200's http responce with message of 'Invalid token'

after some code exploration we found that spring security since version 2.1.1.RELEASE contains code in file RemoteTokenServices.java (https://github.com/spring-projects/spring-security-oauth/blob/2.1.1.RELEASE/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/RemoteTokenServices.java)
which unconditionaly checks field named 'active' in check_token response. But uaa response doesn't contains one.
```java	
// gh-838
if (!Boolean.TRUE.equals(map.get("active"))) {
  logger.debug("check_token returned active attribute: " + map.get("active"));
  throw new InvalidTokenException(accessToken);
}
```
since map.get("active") is null the condition is always true
### Workaround
use dependencyManagement maven feature to force use 2.1.0.RELEASE version of spring-security-oauth2
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.security.oauth</groupId>
				<artifactId>spring-security-oauth2</artifactId>
				<version>2.1.0.RELEASE</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

```

**Comment by jhamon** [comment]
@sreetummidi @fhanik Looks like this broke starting with 2.1.1 https://github.com/spring-projects/spring-security-oauth/commit/f1a9b976389672ff94dfe697d8315256eabc5bf3

They are now validating the required `active` attribute as described in [RFC 7662](https://tools.ietf.org/html/rfc7662#section-2.2). It seems not great they introduced a breaking change in a minor version release.

Since our `/check_token` predates this spec by a couple years, I'm not surprised there's some differences. Besides this `active` attribute, which could be added without disrupting anything to resolve this issue, the spec also says invalid tokens should get response
```
HTTP/1.1 200 OK
Content-Type: application/json

{
   "active": false
}
```

Today we send back a 400 Error with `{"error":"invalid_token","error_description":"The token expired, was revoked, or the token ID is incorrect: foo"}`. That'd be a significant breaking change for us to our API.... not sure how we should approach this.

**Comment by fhanik** [comment]
My suggestion is that we introduce a new endpoint `/oauth/token/introspect` that implements RFC 7662 as a new feature. 

`/check_token` predates RFC 7662 so it naturally does not conform to it.

**Comment by sreetummidi** [comment]
New endpoint being added in UAA 4.9.0
http://docs.cloudfoundry.org/api/uaa/version/release-candidate/#introspect-token
