### ISSUE TITLE
UAA requires client_secret for authorization code client

### ISSUE THREAD

**Issue by ofuangka** [cloudfoundry/uaa#761]
I'm trying to implement SPA authentication _without_ implicit grant using the below method:

https://www.oauth.com/oauth2-servers/oauth2-clients/single-page-apps/
and
https://aaronparecki.com/oauth-2-simplified/#single-page-apps

However, UAA seems to require authentication using the client_secret.  I suspect this is because of what Aaron Parecki's site says, i.e. 

> In the time since the spec was originally written, the industry best practice has changed to recommend that the authorization code flow be used without the client secret.

If this is accurate and UAA does not currently support this flow, is it planned?

**Comment by fhanik** [comment]
`authorization_code` and `implicit` grant types are identical in their functionality with the one difference that implicit grant does not require a client_secret.

If you want this flow to work without a client_secret you'd use a client with implicit grant.

Can you possibly elaborate why you'd want an authorization_code grant without a client secret? Maybe the other servers don't implement implicit grant and thus have to modify their authorization code grant to meet their implicit needs?

**Comment by ofuangka** [comment]
Here is the complete relevant quote from Aaron Parecki's site:

> Note: Previously, it was recommended that browser-based apps use the "Implicit" flow, which returns an access token immediately and does not have a token exchange step. In the time since the spec was originally written, the industry best practice has changed to recommend that the authorization code flow be used without the client secret. This provides more opportunities to create a secure flow, such as using the state parameter.

I could be wrong, but it looks like implicit_grant does not require the token exchange step, which means that the application does not get the chance to verify the consistency between the stored state and returned state.  This makes it easier for malicious users to execute CSRF attacks (see here for a good explanation: https://stackoverflow.com/questions/35985551/how-does-csrf-work-without-state-parameter-in-oauth2-0/35988614#35988614)

**Comment by jhamon** [comment]
As a workaround, it seems like you should be able to create an authcode client and simply leak the secret to the browser. Maybe I am overlooking something, but it seems like having a known secret would be equivalent in security to having a secretless authcode grant client.

From a support and user education perspective, maintaining a distinction between implicit and authcode guides our users toward better security decisions. For example, the implicit grant flow does not support refresh tokens because a refresh token is not a safe or appropriate thing to have in the browser context where it could be stolen or misused. We recommend a more frequent token expiration to implicit grant clients.

It seems like maybe the change we should explore is how to add `state` to the implicit flow, rather than relaxing the requirements we have in place for authcode flow.

**Comment by fhanik** [comment]
@ofuangka your links shows an exploit of an authorization_code grant without a client_secret (or a known client secret), where the code can be exchanged at a later point because the system trapped the URL.

It is inherently important to understand the implicit grant, and that it is insecure because the application/client cannot protect its credentials.

An implicit grant at least sends back the data as a fragment not a query parameter, and thus it doesn't leak out in Referral headers etc.

In my opionion the implicit flow works as well as it can given how insecure it is. There isn't a way to make it more secure, so when choosing that flow you know what you are getting.

I'm of the opinion that the implicit flow doesn't become more secure if you try to make it work like the authorization_code flow but with a known client secret. It just gives you a false sense of confidence.

Your best bet is to add a server state component to your flow if you want something secure and then use the authorization code flow properly. That way the token is never exposed to watching eyes and listening 
ears

**Comment by ofuangka** [comment]
@fhanik Just wanted to clarify--I was hoping to use the authorization_code grant, not the implicit grant for a single page application. 

> authorization_code and implicit grant types are identical in their functionality...

I don't think that's true.  authorization_code requires 2 calls--one to retrieve the code, the other to exchange it for a token.  implicit requires one and only one call to retrieve the token, which makes it vulnerable to the attack linked above.  authorization_code with a state parameter is not vulnerable to the attack above, assuming the single page application is implemented correctly.  This is a real benefit, not a false sense of confidence.  Unfortunately, in order to use UAA's authorization_code flow, the single page application must know the client_secret, which exposes it to everyone.  It would be better if authorization_code did not require the client_secret, at least in the specific case of using it in a single page application.

@jhamon implicit will not work because you always retrieve the token in one step.  It has to be done in two for the state parameter to be useful.

Here is another reference to single page application developers that have begun moving towards using authorization_code flow and state: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/19#issuecomment-343141180

I might be wrong here, and I no longer have an immediate need for this, so feel free to keep it closed, just be aware that more may be asking for this feature in the future.
