### ISSUE TITLE
Account Cookies

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#774]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

4.10.0

### How are you deploying the UAA?

gradlew

### What did you do?

Logon and checked received cookies.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Cookies with secure flags and httpOnly = true

### What did you see instead?

httpOnly = false

---------------
The cookie is sent out in

https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java#L72-L77

and used only if IdpDiscovery is active

https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java#L473-L489

Therefore the cookie should not be written in case IdpDiscovery is not active.

Problem with the cookie is that there are personal information like an email and this information is stored for a year.

**Comment by jhamon** [comment]
As I commented on #775, the `Current-User` cookie is needed for our implementation of OIDC session management. It is intentionally `httpOnly=false` because it must be readable by [javascripts](https://github.com/cloudfoundry/uaa/blob/a4132cbb27f5b444de2a9b85f4f157694bebd6fc/uaa/src/main/webapp/resources/javascripts/session/session.js#L53) running in the UAA's OP iframe; javascripts cannot access cookies that are httpOnly. It may be used whether or not account discovery is in use if there are relying parties using uaa-singular or other library to discover login status. 

This [blog post](https://medium.com/@piraveenaparalogarajah/openid-connect-session-management-dc6a65040cc) gives a pretty good overview of the OIDC session management flow if you're not familiar with how it works. The goal is for relying parties to be notified of a change in user login status without each one having to poll the UAA continuously for updates. The polling is replaced with message passing to a UAA iframe that reads this cookie on the UAA domain to see if a change has occurred in the user's login status (e.g. if the user has logged out in a different browser tab). 

As for the content of the cookie, it is a serialization of the user's guid. It does not contain an email address or other personally identifiable information.

**Comment by tnwang** [comment]
@strehle I think we conflated two different issues in this issue and PR, which I think we can break apart and still be able to achieve the European Data Law related item you were originally after:

1. The `Saved-Account-Cookie` is directly tied to Account Chooser, so the PR can still include this fix, and we only have `Saved-Account-Cookie` when account chooser is enabled. Longer term, we are thinking to move towards local storage with possibly less data, and potentially leverage the OpenID Foundation provided form.

2. For `Current-User` cookie, the data only includes the GUID which should fall under `pseudonymisation` , which per GDPR is an example of a measure designed to implement data-protection principles. It is quite long lived so we can still look at other ways to better protect the information separately, like a shorter lifetime. 

We plan to speak with our legal tomorrow to double check some of our assumptions, and would appreciate if you could weigh in from your side as well, such as if there are concerns with httpOnly=false outside of European Data Law concerns from your security team.
