### ISSUE TITLE
PLEASE update master with 4.19.2

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#872]
from my point of view master should have to latest release, means you released 4.19.2 officially and then master should have rev. from 4.19.2

**Comment by bruce-ricard** [comment]
A bit of background as to how we are currently structuring our branches in the `uaa`:
1) develop has our latest commits
2) we run our develop commits in CI
3) assuming they pass CI, when we want to cut a new release, we perform the following:
3.1) we cut a new release from develop. (This involves creating a github release, and updating the version file)
3.2) we fast forward master to develop
3.3) we create a tag pointing to the commit that we released on
3.4) we create a `prerelease/vM.m.x` branch pointing to the tag that we released
3.5) on develop; we bump the versions file to the next version (snapshot)

On develop future commits are made. When/IF a cve arrises, we make a commit on the `prerelease/vM.m.x` branch. and perform a patch release off that branch. From our perspective, the develop *and* master branch have diverged from the 'prerelease/vM.m.x' branch.
Also we think that the master branch should *only* provide a 'stable' view on develop. In this case it points to a commit that has gone through CI, and also happens to be the latest point release (not the patch).

I think we need to improve the discoverability of what the latest `uaa` release is. for example, the latest github release is not showing `4.19.2` as the latest release and is instead showing `4.12.2`. Github uses the tag timestamp to sort release versions. We *might* be able to improve that so that github releases shows `4.19.2` as the latest.

I personally think we should remove the master branch. I think it is causing confusion. I think we should use a single branch (the develop branch). And continue the 'train line' branch/tag model we currently use for patch releases.

I also don't think that we should merge the latest patch release (e.g. 4.19.2) to master. As discussed above: the commits made to the 4.19 minor release, are to fix issues on that branch, and thus don't necessarily have to be on either master or develop. The release branches fork off master and develop.

Lastly, I *think* this is what we used to do in the scary past (at a time we had manual release scripts):
1) Release 4.19.0
2) push a feature commit
3) push a chore commit
4) fix a CVE
5) Release 4.20.0 with all these commits to fix the CVE

The issue with this is that we are releasing 2 commits earlier that we wanted to (the ones from 2) and 3)), all we really wanted to release to fix the CVE was the commit 4). This is why we fork off the 4.19.0 tag, cherry pick the commit 4), and release from there. We should be waiting for our next minor release to publish all new feature commits, and not be forced to do it at a moment we might not be ready to do so.

**Comment by strehle** [comment]
I support many of your thought, however I thing.

develop should always contain the lastest fixes from a CVE. Releasing for a separate branch but not providing this to develop will increase confusion.

If you argue master is a stable view on develop, then you should also commit CVE fixed which are in develop also to master, e.g.
compare yourself server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java between develop and master. 

You may remove master, but github requires a default branch and the default branch is the branch everybody from outside will have a look first.
And again this default branch should be a stable (and secure branch) means your latest CVE fixes should be in into such a default branch.

You can omit many things if you have only one version, but with this parallel versions uaa supports, a so call master branch is what its name says: it is the master.
Finally: if you have numeric versions, then from human understanding the greatest number is the latest version and also master has a version, but this is lower then another branch has and this might be confusion for all outside developers. because they simple clone the default branch and assume that is the latest version.

So may be we can close this if you release 4.20.0 from develop soon..

**Comment by bruce-ricard** [comment]
If the CVE is also on develop, develop **always** contains the CVE fix. Our typical way of doing this is to fix the issue on develop, and then cherry-pick the commits to the impacted release branches. For completeness sake, if for some reason develop does **not** have the issue from the CVE, for example because a new feature got rid of it, we obviously won't have the CVE fix on develop. So develop does *not* always contain the latest CVE fix commits.

Now after that, what do we do with master as we are creating multiple CVE-related releases? Well, we can either leave it where it is, or fast-forward it to the top of develop where the CVE fixes are. But that is not a release. The release is from the previous patch branch. I don't want to also cherry-pick the CVE fixes to the master branch.

If we delete the `master` branch, `develop` will become our default branch, which contains fixes to all CVEs and bugs that we are aware of, as soon as we have worked on them.

We feel the `master` branch is confusing to everyone, including us, which is why we are discussing whether it can be eliminated. If you want to find a patched release, you should be looking at the tagged release commits. And if you want to submit a PR, the correct thing is to work off of the `develop` branch. So we think `master` currently should not be used for either consuming the UAA or developing the UAA.

What is the use case where you need to consume a "stable branch" that is not a tagged release? The commits we have tagged as releases are the only ones we are confident telling people in the open source community to deploy in their environments.

**Comment by strehle** [comment]
you may first define then develop as default branch so that git clone git@github.com:cloudfoundry/uaa.git sync this branch and not master.

The use case is the first entry to uaa repo. If you sync first you get master because this is defined as default. but currently this branch does not contain the latest CVEs correction, so it is not a stable branch any newbies should use

**Comment by jhamon** [comment]
@strehle We have made `develop` the default branch.
