### ISSUE TITLE
Public information providing overview of CF UAA Versions that get security updates

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#884]
Dear CF UAA team,

Is there currently any place (e.g., web page on Github or elsewhere) available, where one can find the following information:
•	Versions of CF UAA (a) for which security updates will be provided and (b) what is the planned time frame in which it is expected that those versions get updates
•	Versions of CF UAA for which no more security updates will be provided
If such a place is not available yet, is it possible that you start sharing the information above?

E.g. based on the latest releases, it looks like the following versions get updates (yet, it is not clear how long it is planned that the individual versions get updates):
* CF UAA 4.19.x
* CF UAA 4.12.x
* CF UAA 4.10.x
* CF UAA 4.7.x
* CF UAA 4.5.x

For CF UAA 4.8.x seems no further updates beyond 4.8.3 are provided (yet, it is not clear whether this assumption is correct)

**Comment by jhamon** [comment]
If you need critical security fixes you should always upgrade to the latest release of UAA. The release lines you mentioned have received backports of key security fixes in the past because they are included in Pivotal's commercial product offerings, but we don't make any public commitments about long-term support of open source releases. In the future, Pivotal may shift to maintaining these security backports in a private fork of UAA without notice.
