### ISSUE TITLE
Get a user with uaa.admin of uaa service in cloudfoundry

### ISSUE THREAD

**Issue by charlottehu111** [cloudfoundry/uaa#981]
"version": "4.24.0"

UAA instance is created and binded with our application in cloud foundry. In its local environment, we get 
{
	...
	"clientid": "some-client-id",
	"clientsecret": "some-secret",
	"url": "https://oms-dev-cf.authentication.sap.hana.ondemand.com",
	..
}

With clientid and clientsecret and url, we can access uaa instance. But the scope of clientid is uaa.resource.

 I want to visit /users and /Groups, /identity.zone of uaa instance. It requires uaa.admin. So How can I get a admin user from the uaa instance?

Thanks and Best regards
Charlotte

**Comment by andrewedstrom** [comment]
@charlottehu111 I suggest you rotate the client secret that you shared originally ASAP. Client secrets are like passwords and should not be shared publicly.

I don't know the specifics of how your cloud foundry was deployed, but you will likely need to talk to the people who deployed and run your cloud foundry if you want to get an admin user. Admin clients can only be created 1) by another admin, or 2) in the bosh manifest when the UAA is being deployed. Unless you are an admin or the person deploying the CF, there's nothing you can do to make yourself an admin other than reach out to the people who have that power.

I'm closing this since it's a support question rather than an issue with the UAA's functionality. Feel free to reach out on #uaa in the https://cloudfoundry.slack.com if you need more help!
